//! M3: entity_generator.rs 补充测试 — 覆盖 idempotent/from_db/default/BelongsTo/HasOne

use sz_orm_cli::{
    DbColumnSchema, DbForeignKey, DbTableSchema, EntityDefinition, EntityField, EntityGenerator,
    EntityRelation, RelationType,
};

// === EntityField 补充 ===

#[test]
fn test_entity_field_default_flags() {
    let f = EntityField::new("name", "String", "varchar");
    assert!(!f.is_primary_key);
    assert!(!f.nullable);
}

#[test]
fn test_entity_field_primary_key_chain() {
    let f = EntityField::new("id", "i64", "bigint").primary_key();
    assert!(f.is_primary_key);
    assert!(!f.nullable);
}

#[test]
fn test_entity_field_nullable_chain() {
    let f = EntityField::new("email", "String", "varchar").nullable();
    assert!(!f.is_primary_key);
    assert!(f.nullable);
}

#[test]
fn test_entity_field_both_flags() {
    let f = EntityField::new("id", "i64", "bigint")
        .primary_key()
        .nullable();
    assert!(f.is_primary_key);
    assert!(f.nullable);
}

// === EntityGenerator::default ===

#[test]
fn test_entity_generator_default() {
    let gen = EntityGenerator;
    let entity = EntityDefinition::new("Test", "test")
        .with_field(EntityField::new("id", "i64", "bigint").primary_key());
    let code = gen.generate(&entity);
    assert!(code.contains("pub struct Test"));
}

// === generate_idempotent ===

#[test]
fn test_generate_idempotent_has_header() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("User", "users")
        .with_field(EntityField::new("id", "i64", "bigint").primary_key());
    let code = gen.generate_idempotent(&entity);
    assert!(code.contains("@generated by sz-orm-cli"));
    assert!(code.contains("Do not edit manually"));
}

#[test]
fn test_generate_idempotent_sorts_fields() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("User", "users")
        .with_field(EntityField::new("zebra", "String", "varchar"))
        .with_field(EntityField::new("apple", "String", "varchar"))
        .with_field(EntityField::new("mango", "String", "varchar"));
    let code = gen.generate_idempotent(&entity);
    let apple_pos = code.find("pub apple").unwrap();
    let mango_pos = code.find("pub mango").unwrap();
    let zebra_pos = code.find("pub zebra").unwrap();
    assert!(apple_pos < mango_pos);
    assert!(mango_pos < zebra_pos);
}

#[test]
fn test_generate_idempotent_is_deterministic() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("User", "users")
        .with_field(EntityField::new("id", "i64", "bigint").primary_key())
        .with_field(EntityField::new("name", "String", "varchar").nullable());
    let code1 = gen.generate_idempotent(&entity);
    let code2 = gen.generate_idempotent(&entity);
    assert_eq!(code1, code2);
}

#[test]
fn test_generate_idempotent_sorts_relations() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("User", "users")
        .with_field(EntityField::new("id", "i64", "bigint").primary_key())
        .with_relation(EntityRelation {
            relation_type: RelationType::HasMany,
            target_entity: "ZOrder".to_string(),
            local_field: "id".to_string(),
            target_field: "user_id".to_string(),
        })
        .with_relation(EntityRelation {
            relation_type: RelationType::HasOne,
            target_entity: "AProfile".to_string(),
            local_field: "id".to_string(),
            target_field: "user_id".to_string(),
        });
    let code = gen.generate_idempotent(&entity);
    let a_pos = code.find("aprofile").unwrap();
    let z_pos = code.find("zorder").unwrap();
    assert!(a_pos < z_pos);
}

// === generate_all_idempotent ===

#[test]
fn test_generate_all_idempotent_sorts_entities() {
    let gen = EntityGenerator::new();
    let entities = vec![
        EntityDefinition::new("Zebra", "zebras")
            .with_field(EntityField::new("id", "i64", "bigint").primary_key()),
        EntityDefinition::new("Apple", "apples")
            .with_field(EntityField::new("id", "i64", "bigint").primary_key()),
    ];
    let code = gen.generate_all_idempotent(&entities);
    let apple_pos = code.find("pub struct Apple").unwrap();
    let zebra_pos = code.find("pub struct Zebra").unwrap();
    assert!(apple_pos < zebra_pos);
}

#[test]
fn test_generate_all_idempotent_is_deterministic() {
    let gen = EntityGenerator::new();
    let entities = vec![
        EntityDefinition::new("User", "users")
            .with_field(EntityField::new("id", "i64", "bigint").primary_key()),
        EntityDefinition::new("Order", "orders")
            .with_field(EntityField::new("id", "i64", "bigint").primary_key()),
    ];
    let code1 = gen.generate_all_idempotent(&entities);
    let code2 = gen.generate_all_idempotent(&entities);
    assert_eq!(code1, code2);
}

// === RelationType::HasOne ===

#[test]
fn test_generate_has_one_relation() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("User", "users")
        .with_field(EntityField::new("id", "i64", "bigint").primary_key())
        .with_relation(EntityRelation {
            relation_type: RelationType::HasOne,
            target_entity: "Profile".to_string(),
            local_field: "id".to_string(),
            target_field: "user_id".to_string(),
        });
    let code = gen.generate(&entity);
    assert!(code.contains("impl User"));
    assert!(code.contains("fn profile"));
    assert!(code.contains("Option<&Profile>"));
}

// === RelationType::BelongsTo ===

#[test]
fn test_generate_belongs_to_relation() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("Order", "orders")
        .with_field(EntityField::new("id", "i64", "bigint").primary_key())
        .with_relation(EntityRelation {
            relation_type: RelationType::BelongsTo,
            target_entity: "User".to_string(),
            local_field: "user_id".to_string(),
            target_field: "id".to_string(),
        });
    let code = gen.generate(&entity);
    assert!(code.contains("impl Order"));
    assert!(code.contains("fn user"));
    assert!(code.contains("Option<&User>"));
}

// === generate_from_db ===

#[test]
fn test_generate_from_db_basic() {
    let gen = EntityGenerator::new();
    let tables = vec![DbTableSchema {
        name: "users".to_string(),
        columns: vec![
            DbColumnSchema {
                name: "id".to_string(),
                db_type: "bigint".to_string(),
                is_primary_key: true,
                is_nullable: false,
            },
            DbColumnSchema {
                name: "name".to_string(),
                db_type: "varchar".to_string(),
                is_primary_key: false,
                is_nullable: false,
            },
            DbColumnSchema {
                name: "email".to_string(),
                db_type: "varchar".to_string(),
                is_primary_key: false,
                is_nullable: true,
            },
        ],
        foreign_keys: vec![],
    }];
    let code = gen.generate_from_db(&tables);
    assert!(code.contains("pub struct UsersModel"));
    assert!(code.contains("pub id: i64"));
    assert!(code.contains("pub name: String"));
    assert!(code.contains("pub email: Option<String>"));
}

#[test]
fn test_generate_from_db_with_foreign_keys() {
    let gen = EntityGenerator::new();
    let tables = vec![DbTableSchema {
        name: "orders".to_string(),
        columns: vec![DbColumnSchema {
            name: "id".to_string(),
            db_type: "bigint".to_string(),
            is_primary_key: true,
            is_nullable: false,
        }],
        foreign_keys: vec![DbForeignKey {
            local_column: "user_id".to_string(),
            target_table: "users".to_string(),
            target_column: "id".to_string(),
        }],
    }];
    let code = gen.generate_from_db(&tables);
    assert!(code.contains("pub struct OrdersModel"));
    // generate() 按 RelationType::BelongsTo 生成关系方法 `pub fn usersmodel`
    // （枚举名本身不进入生成代码，见 entity_generator.rs:145）
    assert!(code.contains("pub fn usersmodel"));
    assert!(code.contains("UsersModel"));
}

#[test]
fn test_generate_from_db_multiple_tables() {
    let gen = EntityGenerator::new();
    let tables = vec![
        DbTableSchema {
            name: "users".to_string(),
            columns: vec![DbColumnSchema {
                name: "id".to_string(),
                db_type: "bigint".to_string(),
                is_primary_key: true,
                is_nullable: false,
            }],
            foreign_keys: vec![],
        },
        DbTableSchema {
            name: "orders".to_string(),
            columns: vec![DbColumnSchema {
                name: "id".to_string(),
                db_type: "bigint".to_string(),
                is_primary_key: true,
                is_nullable: false,
            }],
            foreign_keys: vec![],
        },
    ];
    let code = gen.generate_from_db(&tables);
    assert!(code.contains("pub struct UsersModel"));
    assert!(code.contains("pub struct OrdersModel"));
}

// === infer_rust_type 补充 ===

#[test]
fn test_infer_rust_type_serial() {
    assert_eq!(EntityGenerator::infer_rust_type("serial"), "i64");
}

#[test]
fn test_infer_rust_type_double() {
    assert_eq!(EntityGenerator::infer_rust_type("double precision"), "f64");
}

#[test]
fn test_infer_rust_type_decimal() {
    assert_eq!(EntityGenerator::infer_rust_type("decimal(10,2)"), "f64");
}

#[test]
fn test_infer_rust_type_numeric() {
    assert_eq!(EntityGenerator::infer_rust_type("numeric"), "f64");
}

#[test]
fn test_infer_rust_type_real() {
    assert_eq!(EntityGenerator::infer_rust_type("real"), "f64");
}

#[test]
fn test_infer_rust_type_text() {
    assert_eq!(EntityGenerator::infer_rust_type("text"), "String");
}

#[test]
fn test_infer_rust_type_jsonb() {
    assert_eq!(
        EntityGenerator::infer_rust_type("jsonb"),
        "serde_json::Value"
    );
}

// === EntityDefinition 空实体 ===

#[test]
fn test_generate_empty_entity() {
    let gen = EntityGenerator::new();
    let entity = EntityDefinition::new("Empty", "empty");
    let code = gen.generate(&entity);
    assert!(code.contains("pub struct Empty"));
    assert!(code.contains("}"));
}

#[test]
fn test_generate_all_empty() {
    let gen = EntityGenerator::new();
    let code = gen.generate_all(&[]);
    assert!(code.is_empty());
}

#[test]
fn test_generate_all_idempotent_empty() {
    let gen = EntityGenerator::new();
    let code = gen.generate_all_idempotent(&[]);
    assert!(code.is_empty());
}
#[test]
fn test_infer_rust_type_int() {
    assert_eq!(EntityGenerator::infer_rust_type("INTEGER"), "i64");
    assert_eq!(EntityGenerator::infer_rust_type("BIGINT"), "i64");
    assert_eq!(EntityGenerator::infer_rust_type("smallint"), "i64");
}

#[test]
fn test_infer_rust_type_bool() {
    assert_eq!(EntityGenerator::infer_rust_type("BOOLEAN"), "bool");
    assert_eq!(EntityGenerator::infer_rust_type("bool"), "bool");
}

#[test]
fn test_infer_rust_type_float() {
    assert_eq!(EntityGenerator::infer_rust_type("FLOAT"), "f64");
    assert_eq!(EntityGenerator::infer_rust_type("float8"), "f64");
}

#[test]
fn test_infer_rust_type_json() {
    assert_eq!(
        EntityGenerator::infer_rust_type("JSON"),
        "serde_json::Value"
    );
    assert_eq!(
        EntityGenerator::infer_rust_type("jsonb"),
        "serde_json::Value"
    );
}

#[test]
fn test_infer_rust_type_string_default() {
    assert_eq!(EntityGenerator::infer_rust_type("VARCHAR(255)"), "String");
    assert_eq!(EntityGenerator::infer_rust_type("TEXT"), "String");
    assert_eq!(EntityGenerator::infer_rust_type("CHAR(10)"), "String");
    assert_eq!(EntityGenerator::infer_rust_type("DATE"), "String");
    assert_eq!(EntityGenerator::infer_rust_type("TIMESTAMP"), "String");
}

#[test]
fn test_generate_has_many_relation() {
    let mut entity = EntityDefinition::new("User", "users");
    entity = entity.with_relation(EntityRelation {
        relation_type: RelationType::HasMany,
        target_entity: "Order".to_string(),
        local_field: "id".to_string(),
        target_field: "user_id".to_string(),
    });
    let gen = EntityGenerator::new();
    let code = gen.generate(&entity);
    assert!(code.contains("fn orders(&self) -> Vec<Order>"));
    assert!(code.contains("Vec::new()"));
}

#[test]
fn test_generate_nullable_field() {
    let mut entity = EntityDefinition::new("User", "users");
    entity = entity.with_field(EntityField::new("email", "String", "VARCHAR(255)").nullable());
    let gen = EntityGenerator::new();
    let code = gen.generate(&entity);
    assert!(code.contains("pub email: Option<String>"));
}

#[test]
fn test_generate_primary_key_field() {
    let mut entity = EntityDefinition::new("User", "users");
    entity = entity.with_field(EntityField::new("id", "i64", "BIGINT").primary_key());
    let gen = EntityGenerator::new();
    let code = gen.generate(&entity);
    assert!(code.contains("/// Primary key"));
    assert!(code.contains("pub id: i64"));
}

#[test]
fn test_generate_from_db_nullable_and_primary_key() {
    let tables = vec![DbTableSchema {
        name: "users".to_string(),
        columns: vec![
            DbColumnSchema {
                name: "id".to_string(),
                db_type: "BIGINT".to_string(),
                is_primary_key: true,
                is_nullable: false,
            },
            DbColumnSchema {
                name: "email".to_string(),
                db_type: "VARCHAR(255)".to_string(),
                is_primary_key: false,
                is_nullable: true,
            },
        ],
        foreign_keys: vec![],
    }];
    let gen = EntityGenerator::new();
    let code = gen.generate_from_db(&tables);
    assert!(code.contains("pub id: i64"));
    assert!(code.contains("pub email: Option<String>"));
    assert!(code.contains("/// Primary key"));
}
