/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sz_orm_java_SzOrmPool */

#ifndef _Included_sz_orm_java_SzOrmPool
#define _Included_sz_orm_java_SzOrmPool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sz_orm_java_SzOrmPool
 * Method:    poolNew
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_sz_1orm_1java_SzOrmPool_poolNew
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     sz_orm_java_SzOrmPool
 * Method:    poolFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sz_1orm_1java_SzOrmPool_poolFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sz_orm_java_SzOrmPool
 * Method:    ping
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sz_1orm_1java_SzOrmPool_ping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sz_orm_java_SzOrmPool
 * Method:    query
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sz_1orm_1java_SzOrmPool_query
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     sz_orm_java_SzOrmPool
 * Method:    execute
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sz_1orm_1java_SzOrmPool_execute
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     sz_orm_java_SzOrmPool
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sz_1orm_1java_SzOrmPool_version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
