//! 跨数据库 + 跨 ORM 横向对比基准（harness = false，自定义 main）
//!
//! # 矩阵
//!
//! | 数据库     | SZ-ORM | sqlx | diesel | sea-orm | raw oracle | 触发方式                  |
//! |-----------|:------:|:----:|:------:|:-------:|:----------:|--------------------------|
//! | SQLite    |   ✓    |  ✓   |   ✓    |   ✓     |     -      | 始终运行（in-memory）     |
//! | MySQL     |   ✓    |  ✓   |   ✓    |   ✓     |     -      | `DATABASE_URL_MYSQL`      |
//! | PostgreSQL|   ✓    |  ✓   |   ✓    |   ✓     |     -      | `DATABASE_URL_POSTGRES`   |
//! | Oracle    |   ✓    |  -   |   -    |   -     |     ✓      | `DATABASE_URL_ORACLE`     |
//!
//! # 场景（每 DB × 每 ORM）
//!
//! - INSERT 1K rows    （SQLite/远程均 1K；文件 DB + WAL 每行 fsync，1K 足够观察 ORM 开销）
//! - SELECT BY ID 100× （所有 DB 一致）
//! - SELECT ALL 1K     （所有 DB 一致）
//! - UPDATE 100 rows   （所有 DB 一致）
//! - DELETE 1K rows    （所有 DB 一致）
//!
//! # SZ-ORM 优化路径
//!
//! - INSERT/UPDATE/DELETE 使用 `execute_with_params`（真实 prepared statement）
//! - SELECT BY ID 使用 `query_with_params`
//! - SELECT ALL 使用 `query_values`（位置式映射，绕过 HashMap 开销）
//!
//! # 用法
//!
//! ```bash
//! # 仅 SQLite（in-memory，始终运行）
//! cargo bench --bench cross_db_comparison
//!
//! # 全数据库（需提供连接串）
//! $env:DATABASE_URL_MYSQL="mysql://user:pass@host:3306/db"
//! $env:DATABASE_URL_POSTGRES="postgres://user:pass@host:5432/db"
//! $env:DATABASE_URL_ORACLE="user/pass@//host:1521/service"
//! cargo bench --bench cross_db_comparison
//! ```

use std::env;
use std::sync::Arc;
use std::time::{Duration, Instant};

#[allow(unused_imports)]
use diesel::prelude::*;
use sea_orm::{ConnectOptions, ConnectionTrait, Database, DatabaseBackend, DatabaseConnection, Statement};
use sz_orm_core::{Pool as SzPool, PoolConfigBuilder, Value};
use sz_orm_sqlx::{
    MySqlPoolHandle, PgPoolHandle, SqlitePoolHandle, SqlxMySqlConnectionFactory, SqlxPgConnectionFactory,
    SqlxSqliteConnectionFactory,
};

#[cfg(feature = "oracle")]
use oracle as oracle_crate;

type BoxError = Box<dyn std::error::Error + Send + Sync>;

// ============================================================================
// cfg-gated 类型别名（diesel mysql/pg 在未启用 feature 时用 () 占位，编译通过但跳过执行）
// ============================================================================

#[cfg(feature = "diesel-mysql")]
type DieselMysqlConn = diesel::mysql::MysqlConnection;
#[cfg(not(feature = "diesel-mysql"))]
type DieselMysqlConn = ();

#[cfg(feature = "diesel-postgres")]
type DieselPgConn = diesel::pg::PgConnection;
#[cfg(not(feature = "diesel-postgres"))]
type DieselPgConn = ();

/// 打印 "diesel (skipped)" 行
fn print_diesel_skipped(reason: &str) {
    let mut row = String::from("| diesel |");
    for _ in 0..TRIALS {
        row.push_str(" skipped |");
    }
    row.push_str(&format!(" - ({}) |", reason));
    println!("{}", row);
}

// ============================================================================
// 常量
// ============================================================================

/// SQLite 数据量（文件 DB + WAL，每行 INSERT 自带 fsync；用 1K 行避免基准跑过久）
const SQLITE_ROWS: usize = 1_000;
const SQLITE_QUERIES: usize = 100;

/// 远程数据库数据量（受网络 RTT 限制，1K 即可）
const REMOTE_ROWS: usize = 1_000;
const REMOTE_QUERIES: usize = 100;

/// 重复测试次数（取中位数）
const TRIALS: usize = 3;

// ============================================================================
// 表结构（每库一份，因语法差异）
// ============================================================================

const SQLITE_CREATE: &str = "CREATE TABLE IF NOT EXISTS bench_users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    age INTEGER NOT NULL
)";
const SQLITE_DROP: &str = "DROP TABLE IF EXISTS bench_users";
const SQLITE_TRUNCATE: &str = "DELETE FROM bench_users";

const MYSQL_CREATE: &str = "CREATE TABLE IF NOT EXISTS bench_users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age INT NOT NULL
)";
const MYSQL_TRUNCATE: &str = "TRUNCATE TABLE bench_users";

const PG_CREATE: &str = "CREATE TABLE IF NOT EXISTS bench_users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    age INT NOT NULL
)";
const PG_TRUNCATE: &str = "TRUNCATE TABLE bench_users RESTART IDENTITY";

const ORACLE_CREATE: &str = "CREATE TABLE bench_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    age NUMBER(10) NOT NULL
)";
const ORACLE_DROP: &str = "DROP TABLE bench_users";
const ORACLE_TRUNCATE: &str = "TRUNCATE TABLE bench_users";

// ============================================================================
// 辅助函数
// ============================================================================

fn fmt_dur(d: Duration) -> String {
    let ns = d.as_nanos();
    if ns < 1_000 {
        format!("{} ns", ns)
    } else if ns < 1_000_000 {
        format!("{:.2} µs", ns as f64 / 1_000.0)
    } else if ns < 1_000_000_000 {
        format!("{:.2} ms", ns as f64 / 1_000_000.0)
    } else {
        format!("{:.2} s", ns as f64 / 1_000_000_000.0)
    }
}

fn median(mut durs: Vec<Duration>) -> Duration {
    if durs.is_empty() {
        return Duration::default();
    }
    durs.sort();
    durs[durs.len() / 2]
}

fn print_header() {
    let mut header = String::from("| ORM |");
    let mut sep = String::from("|-----|");
    for i in 0..TRIALS {
        header.push_str(&format!(" Trial {} |", i + 1));
        sep.push_str("------|");
    }
    header.push_str(" Median |");
    sep.push_str("--------|");
    println!("{}", header);
    println!("{}", sep);
}

fn print_row(name: &str, times: &[Duration]) {
    let med = median(times.to_vec());
    let trials_str: Vec<String> = times.iter().map(|t| fmt_dur(*t)).collect();
    println!("| {} | {} | {} |", name, trials_str.join(" | "), fmt_dur(med));
}

/// 屏蔽密码后输出 URL
fn mask_url(url: &str) -> String {
    if let Some(at) = url.find('@') {
        if let Some(colon) = url.find(':') {
            if colon < at {
                let scheme_end = url.find("://").map(|i| i + 3).unwrap_or(0);
                if scheme_end <= colon {
                    let mut masked = String::new();
                    masked.push_str(&url[..colon + 1]);
                    masked.push_str("***");
                    masked.push_str(&url[at..]);
                    return masked;
                }
            }
        }
    }
    url.to_string()
}

/// 批量插入 setup 数据（多行 VALUES 减少网络 RTT）
async fn batch_insert_sqlite(sqlx_pool: &sqlx::SqlitePool, n: usize, batch_size: usize) -> Result<(), BoxError> {
    let mut inserted = 0;
    while inserted < n {
        let batch_end = (inserted + batch_size).min(n);
        let mut sql = String::from("INSERT INTO bench_users (name, email, age) VALUES ");
        for i in inserted..batch_end {
            if i > inserted {
                sql.push(',');
            }
            sql.push_str(&format!("('user_{}', 'user_{}@test.com', {})", i, i, i % 100));
        }
        let sql_ref = sql;
        sqlx::query(sqlx::AssertSqlSafe(&*sql_ref)).execute(sqlx_pool).await?;
        inserted = batch_end;
    }
    Ok(())
}

async fn batch_insert_mysql(sqlx_pool: &sqlx::MySqlPool, n: usize, batch_size: usize) -> Result<(), BoxError> {
    let mut inserted = 0;
    while inserted < n {
        let batch_end = (inserted + batch_size).min(n);
        let mut sql = String::from("INSERT INTO bench_users (name, email, age) VALUES ");
        for i in inserted..batch_end {
            if i > inserted {
                sql.push(',');
            }
            sql.push_str(&format!("('user_{}', 'user_{}@test.com', {})", i, i, i % 100));
        }
        let sql_ref = sql;
        sqlx::query(sqlx::AssertSqlSafe(&*sql_ref)).execute(sqlx_pool).await?;
        inserted = batch_end;
    }
    Ok(())
}

async fn batch_insert_pg(sqlx_pool: &sqlx::PgPool, n: usize, batch_size: usize) -> Result<(), BoxError> {
    let mut inserted = 0;
    while inserted < n {
        let batch_end = (inserted + batch_size).min(n);
        let mut sql = String::from("INSERT INTO bench_users (name, email, age) VALUES ");
        for i in inserted..batch_end {
            if i > inserted {
                sql.push(',');
            }
            sql.push_str(&format!("('user_{}', 'user_{}@test.com', {})", i, i, i % 100));
        }
        let sql_ref = sql;
        sqlx::query(sqlx::AssertSqlSafe(&*sql_ref)).execute(sqlx_pool).await?;
        inserted = batch_end;
    }
    Ok(())
}

/// Oracle 批量插入（Oracle 不支持多行 VALUES，使用 INSERT ALL）
fn batch_insert_oracle_stmt(n: usize, batch_size: usize) -> String {
    let mut sql = String::from("INSERT ALL ");
    let mut inserted = 0;
    while inserted < n {
        let batch_end = (inserted + batch_size).min(n);
        for i in inserted..batch_end {
            sql.push_str(&format!(
                "INTO bench_users (name, email, age) VALUES ('user_{}', 'user_{}@test.com', {}) ",
                i, i, i % 100
            ));
        }
        inserted = batch_end;
    }
    sql.push_str("SELECT 1 FROM DUAL");
    sql
}

// ============================================================================
// SQLite benchmark（in-memory，4 ORM 全对比）
// ============================================================================

async fn run_sqlite_bench() -> Result<(), BoxError> {
    println!("## SQLite Benchmark (file DB + WAL, shared across ORMs)\n");
    println!("Rows per scenario: {} (queries: {})\n", SQLITE_ROWS, SQLITE_QUERIES);

    // 使用临时文件 DB 替代 in-memory，让 sqlx/sea-orm/diesel 三个 ORM 共享同一份数据
    // in-memory + cache=shared 在 sqlx 0.9 + diesel + sea-orm 三方间存在兼容性问题
    let tmp_path = std::env::temp_dir().join(format!(
        "sz_orm_bench_{}.sqlite",
        std::process::id()
    ));
    // 清理可能残留的旧文件
    let _ = std::fs::remove_file(&tmp_path);

    // sqlx 0.9 SQLite URL 格式：`sqlite://{path}?mode=rwc`
    // 源码逻辑（sqlx-sqlite-0.9.0/src/options/parse.rs::from_str）：
    //   1. trim_start_matches("sqlite://") 剥掉前缀，剩下 `{path}?mode=rwc`
    //   2. 按 `?` 拆分得到 database={path}, params="mode=rwc"
    //   3. Path::new(database) 直接当文件路径用
    // 所以两斜杠即可（不要三斜杠，否则 path 会多一个前导 `/`）
    // mode=rwc 启用 create_if_missing
    let tmp_path_str = tmp_path.display().to_string().replace('\\', "/");
    let sqlite_url = format!("sqlite://{}?mode=rwc", tmp_path_str);

    // 创建 sqlx pool（同时充当 SZ-ORM 的底层 pool）
    let sqlx_pool = sqlx::sqlite::SqlitePoolOptions::new()
        .max_connections(10)
        .connect(&sqlite_url)
        .await?;
    sqlx::query(SQLITE_CREATE).execute(&sqlx_pool).await?;

    // SZ-ORM SQLite（共享同一 sqlx pool，确保数据一致）
    let sz_handle = Arc::new(SqlitePoolHandle::from_pool(sqlx_pool.clone()));
    let sz_factory = Arc::new(SqlxSqliteConnectionFactory::new(sz_handle.clone()));
    let sz_config = PoolConfigBuilder::new().max_size(10).build()?;
    let sz_pool = SzPool::new(sz_config, sz_factory)?;

    // SeaORM SQLite（用相同 URL，共享同一 DB）
    let mut sea_opt = ConnectOptions::new(sqlite_url.clone());
    sea_opt.max_connections(10);
    let sea_db = Database::connect(sea_opt).await?;

    // Diesel SQLite（用相同文件路径，共享同一 DB）
    let mut diesel_conn = diesel::sqlite::SqliteConnection::establish(&tmp_path.display().to_string())
        .map_err(|e| -> BoxError {
            format!("diesel sqlite connect failed: {}", e).into()
        })?;
    diesel::sql_query(SQLITE_CREATE).execute(&mut diesel_conn)?;

    let n = SQLITE_ROWS;
    let queries = SQLITE_QUERIES;

    bench_sqlite_insert(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;
    bench_sqlite_select_by_id(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n, queries).await?;
    bench_sqlite_select_all(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;
    bench_sqlite_update(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n, queries).await?;
    bench_sqlite_delete(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;

    // 清理
    sqlx::query(SQLITE_DROP).execute(&sqlx_pool).await?;
    sz_pool.close_all().await;
    sqlx_pool.close().await;
    let _ = sea_db.close().await;
    diesel::sql_query(SQLITE_DROP).execute(&mut diesel_conn).ok();
    // 删除临时 DB 文件
    let _ = std::fs::remove_file(&tmp_path);
    let _ = std::fs::remove_file(format!("{}-wal", tmp_path.display()));
    let _ = std::fs::remove_file(format!("{}-shm", tmp_path.display()));

    Ok(())
}

async fn bench_sqlite_insert(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::SqlitePool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut diesel::sqlite::SqliteConnection,
    n: usize,
) -> Result<(), BoxError> {
    println!("### INSERT {} (SQLite)\n", n);
    print_header();

    // SZ-ORM（execute_with_params，真实 prepared statement）
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)",
                &[
                    Value::String(format!("user_{}", i)),
                    Value::String(format!("user_{}@test.com", i)),
                    Value::I32((i % 100) as i32),
                ],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            sqlx::query("INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)")
                .bind(format!("user_{}", i))
                .bind(format!("user_{}@test.com", i))
                .bind((i % 100) as i32)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel（同步）
    let mut diesel_times = Vec::new();
    for _ in 0..TRIALS {
        diesel::sql_query(SQLITE_TRUNCATE).execute(diesel_conn)?;
        let start = Instant::now();
        for i in 0..n {
            diesel::sql_query("INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)")
                .bind::<diesel::sql_types::Text, _>(format!("user_{}", i))
                .bind::<diesel::sql_types::Text, _>(format!("user_{}@test.com", i))
                .bind::<diesel::sql_types::Integer, _>((i % 100) as i32)
                .execute(diesel_conn)?;
        }
        diesel_times.push(start.elapsed());
    }
    print_row("diesel", &diesel_times);

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::Sqlite,
                "INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)",
                vec![
                    format!("user_{}", i).into(),
                    format!("user_{}@test.com", i).into(),
                    ((i % 100) as i32).into(),
                ],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_sqlite_select_by_id(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::SqlitePool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut diesel::sqlite::SqliteConnection,
    prepare_n: usize,
    queries: usize,
) -> Result<(), BoxError> {
    println!(
        "### SELECT BY ID (SQLite, pre-insert {} rows, {} queries)\n",
        prepare_n, queries
    );
    print_header();

    // 预插入数据
    sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_sqlite(sqlx_pool, prepare_n, 500).await?;
    // 同步 diesel 数据（diesel 独立 in-memory，需自行插入）
    for i in 0..prepare_n {
        diesel::sql_query("INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)")
            .bind::<diesel::sql_types::Text, _>(format!("user_{}", i))
            .bind::<diesel::sql_types::Text, _>(format!("user_{}@test.com", i))
            .bind::<diesel::sql_types::Integer, _>((i % 100) as i32)
            .execute(diesel_conn)?;
    }

    // SZ-ORM（query_with_params）
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            let _rows = conn
                .query_with_params(
                    "SELECT name, email, age FROM bench_users WHERE id = ?",
                    &[Value::I64(id)],
                )
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let _ = sqlx::query("SELECT name, email, age FROM bench_users WHERE id = ?")
                .bind(id)
                .fetch_one(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    let mut diesel_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            use diesel::sql_types::*;
            #[derive(QueryableByName)]
            struct UserRow {
                #[diesel(sql_type = Text)]
                name: String,
                #[diesel(sql_type = Text)]
                email: String,
                #[diesel(sql_type = Integer)]
                age: i32,
            }
            let _row: UserRow = diesel::sql_query("SELECT name, email, age FROM bench_users WHERE id = ?")
                .bind::<BigInt, _>(id)
                .get_result(diesel_conn)?;
        }
        diesel_times.push(start.elapsed());
    }
    print_row("diesel", &diesel_times);

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let _ = sea_db
                .query_one(Statement::from_sql_and_values(
                    DatabaseBackend::Sqlite,
                    "SELECT name, email, age FROM bench_users WHERE id = ?",
                    vec![id.into()],
                ))
                .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_sqlite_select_all(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::SqlitePool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut diesel::sqlite::SqliteConnection,
    n: usize,
) -> Result<(), BoxError> {
    println!("### SELECT ALL (SQLite, {} rows)\n", n);
    print_header();

    // 数据已由 select_by_id 预插入；若直接运行此函数，需重新 setup
    let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM bench_users")
        .fetch_one(sqlx_pool)
        .await?;
    if count as usize != n {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_sqlite(sqlx_pool, n, 500).await?;
    }

    // SZ-ORM（query_values，位置式映射，绕过 HashMap）
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let (cols, rows) = conn
            .query_values("SELECT id, name, email, age FROM bench_users")
            .await?;
        sz_times.push(start.elapsed());
        let _ = (cols.len(), rows.len());
    }
    print_row("sz-orm (values)", &sz_times);

    // SZ-ORM（query_with_params，HashMap 映射，对比位置式优化效果）
    let mut sz_hash_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let rows = conn
            .query_with_params("SELECT id, name, email, age FROM bench_users", &[])
            .await?;
        sz_hash_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sz-orm (hashmap)", &sz_hash_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let rows = sqlx::query("SELECT id, name, email, age FROM bench_users")
            .fetch_all(sqlx_pool)
            .await?;
        sqlx_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    let mut diesel_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        use diesel::sql_types::*;
        #[derive(QueryableByName)]
        struct UserRowAll {
            #[diesel(sql_type = BigInt)]
            id: i64,
            #[diesel(sql_type = Text)]
            name: String,
            #[diesel(sql_type = Text)]
            email: String,
            #[diesel(sql_type = Integer)]
            age: i32,
        }
        let rows: Vec<UserRowAll> = diesel::sql_query("SELECT id, name, email, age FROM bench_users")
            .get_results(diesel_conn)?;
        diesel_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("diesel", &diesel_times);

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let rows = sea_db
            .query_all(Statement::from_sql_and_values(
                DatabaseBackend::Sqlite,
                "SELECT id, name, email, age FROM bench_users",
                vec![],
            ))
            .await?;
        sea_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_sqlite_update(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::SqlitePool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut diesel::sqlite::SqliteConnection,
    prepare_n: usize,
    updates: usize,
) -> Result<(), BoxError> {
    println!(
        "### UPDATE (SQLite, pre-insert {} rows, {} updates)\n",
        prepare_n, updates
    );
    print_header();

    // 数据已预插入；若 count != n 则补 setup
    let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM bench_users")
        .fetch_one(sqlx_pool)
        .await?;
    if count as usize != prepare_n {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_sqlite(sqlx_pool, prepare_n, 500).await?;
    }

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "UPDATE bench_users SET name = ? WHERE id = ?",
                &[Value::String("updated_name".to_string()), Value::I64(id)],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            sqlx::query("UPDATE bench_users SET name = ? WHERE id = ?")
                .bind("updated_name")
                .bind(id)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    let mut diesel_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            diesel::sql_query("UPDATE bench_users SET name = ? WHERE id = ?")
                .bind::<diesel::sql_types::Text, _>("updated_name")
                .bind::<diesel::sql_types::BigInt, _>(id)
                .execute(diesel_conn)?;
        }
        diesel_times.push(start.elapsed());
    }
    print_row("diesel", &diesel_times);

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::Sqlite,
                "UPDATE bench_users SET name = ? WHERE id = ?",
                vec!["updated_name".into(), id.into()],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_sqlite_delete(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::SqlitePool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut diesel::sqlite::SqliteConnection,
    n: usize,
) -> Result<(), BoxError> {
    println!("### DELETE {} (SQLite, one-by-one)\n", n);
    print_header();

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_sqlite(sqlx_pool, n, 500).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "DELETE FROM bench_users WHERE id = ?",
                &[Value::I64(id)],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_sqlite(sqlx_pool, n, 500).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            sqlx::query("DELETE FROM bench_users WHERE id = ?")
                .bind(id)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    let mut diesel_times = Vec::new();
    for _ in 0..TRIALS {
        diesel::sql_query(SQLITE_TRUNCATE).execute(diesel_conn)?;
        for i in 0..n {
            diesel::sql_query("INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)")
                .bind::<diesel::sql_types::Text, _>(format!("user_{}", i))
                .bind::<diesel::sql_types::Text, _>(format!("user_{}@test.com", i))
                .bind::<diesel::sql_types::Integer, _>((i % 100) as i32)
                .execute(diesel_conn)?;
        }
        let start = Instant::now();
        for id in 1..=(n as i64) {
            diesel::sql_query("DELETE FROM bench_users WHERE id = ?")
                .bind::<diesel::sql_types::BigInt, _>(id)
                .execute(diesel_conn)?;
        }
        diesel_times.push(start.elapsed());
    }
    print_row("diesel", &diesel_times);

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(SQLITE_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_sqlite(sqlx_pool, n, 500).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::Sqlite,
                "DELETE FROM bench_users WHERE id = ?",
                vec![id.into()],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

// ============================================================================
// MySQL benchmark（4 ORM 全对比）
// ============================================================================

async fn ensure_mysql_database(url: &str) -> Result<(), BoxError> {
    if let Some(db_start) = url.rfind('/') {
        let db_name = &url[db_start + 1..];
        if !db_name.is_empty() {
            let base_url = format!("{}/mysql", &url[..db_start]);
            let pool = sqlx::mysql::MySqlPoolOptions::new()
                .max_connections(1)
                .connect(&base_url)
                .await?;
            let create_sql = format!("CREATE DATABASE IF NOT EXISTS `{}`", db_name);
            sqlx::query(sqlx::AssertSqlSafe(&*create_sql)).execute(&pool).await?;
            pool.close().await;
            println!("[setup] MySQL database '{}' ensured", db_name);
        }
    }
    Ok(())
}

async fn run_mysql_bench(url: &str) -> Result<(), BoxError> {
    println!("## MySQL Benchmark\n");
    println!("Connection: `{}`", mask_url(url));
    println!("Rows per scenario: {} (queries: {})\n", REMOTE_ROWS, REMOTE_QUERIES);

    ensure_mysql_database(url).await?;

    // SZ-ORM MySQL
    let sz_handle = Arc::new(MySqlPoolHandle::connect(url).await?);
    let sz_factory = Arc::new(SqlxMySqlConnectionFactory::new(sz_handle.clone()));
    let sz_config = PoolConfigBuilder::new().max_size(10).build()?;
    let sz_pool = SzPool::new(sz_config, sz_factory)?;

    // sqlx MySQL
    let sqlx_pool = sqlx::mysql::MySqlPoolOptions::new()
        .max_connections(10)
        .connect(url)
        .await?;

    // SeaORM MySQL
    let mut opt = ConnectOptions::new(url.to_string());
    opt.max_connections(10);
    let sea_db = Database::connect(opt).await?;

    // Diesel MySQL
    #[cfg(feature = "diesel-mysql")]
    let mut diesel_conn = diesel::mysql::MysqlConnection::establish(url).map_err(|e| -> BoxError {
        format!("diesel mysql connect failed: {}", e).into()
    })?;
    #[cfg(not(feature = "diesel-mysql"))]
    let mut diesel_conn: DieselMysqlConn = ();

    // 创建表
    sqlx::query(MYSQL_CREATE).execute(&sqlx_pool).await?;

    let n = REMOTE_ROWS;
    let queries = REMOTE_QUERIES;

    bench_mysql_insert(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;
    bench_mysql_select_by_id(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n, queries).await?;
    bench_mysql_select_all(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;
    bench_mysql_update(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n, queries).await?;
    bench_mysql_delete(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;

    // 清理
    sqlx::query("DROP TABLE IF EXISTS bench_users").execute(&sqlx_pool).await?;
    sz_pool.close_all().await;
    sqlx_pool.close().await;
    let _ = sea_db.close().await;

    Ok(())
}

async fn bench_mysql_insert(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::MySqlPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselMysqlConn,
    n: usize,
) -> Result<(), BoxError> {
    println!("### INSERT {} (MySQL)\n", n);
    print_header();

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)",
                &[
                    Value::String(format!("user_{}", i)),
                    Value::String(format!("user_{}@test.com", i)),
                    Value::I32((i % 100) as i32),
                ],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            sqlx::query("INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)")
                .bind(format!("user_{}", i))
                .bind(format!("user_{}@test.com", i))
                .bind((i % 100) as i32)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-mysql")]
    {
        #[cfg(feature = "diesel-mysql")]
        {
            let mut diesel_times = Vec::new();
            for _ in 0..TRIALS {
                diesel::sql_query(MYSQL_TRUNCATE).execute(diesel_conn)?;
                let start = Instant::now();
                for i in 0..n {
                    diesel::sql_query("INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)")
                        .bind::<diesel::sql_types::Text, _>(format!("user_{}", i))
                        .bind::<diesel::sql_types::Text, _>(format!("user_{}@test.com", i))
                        .bind::<diesel::sql_types::Integer, _>((i % 100) as i32)
                        .execute(diesel_conn)?;
                }
                diesel_times.push(start.elapsed());
            }
            print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::MySql,
                "INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)",
                vec![
                    format!("user_{}", i).into(),
                    format!("user_{}@test.com", i).into(),
                    ((i % 100) as i32).into(),
                ],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_mysql_select_by_id(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::MySqlPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselMysqlConn,
    prepare_n: usize,
    queries: usize,
) -> Result<(), BoxError> {
    println!(
        "### SELECT BY ID (MySQL, pre-insert {} rows, {} queries)\n",
        prepare_n, queries
    );
    print_header();

    sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_mysql(sqlx_pool, prepare_n, 100).await?;

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            let _rows = conn
                .query_with_params(
                    "SELECT name, email, age FROM bench_users WHERE id = ?",
                    &[Value::I64(id)],
                )
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let _ = sqlx::query("SELECT name, email, age FROM bench_users WHERE id = ?")
                .bind(id)
                .fetch_one(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-mysql")]
    {
        let mut diesel_times = Vec::new();
        for _ in 0..TRIALS {
            let start = Instant::now();
            for i in 0..queries {
                let id = (i % prepare_n) as i64 + 1;
                use diesel::sql_types::*;
                #[derive(QueryableByName)]
                struct UserRow {
                    #[diesel(sql_type = Text)]
                    name: String,
                    #[diesel(sql_type = Text)]
                    email: String,
                    #[diesel(sql_type = Integer)]
                    age: i32,
                }
                let _row: UserRow = diesel::sql_query("SELECT name, email, age FROM bench_users WHERE id = ?")
                    .bind::<BigInt, _>(id)
                    .get_result(diesel_conn)?;
            }
            diesel_times.push(start.elapsed());
        }
        print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let _ = sea_db
                .query_one(Statement::from_sql_and_values(
                    DatabaseBackend::MySql,
                    "SELECT name, email, age FROM bench_users WHERE id = ?",
                    vec![id.into()],
                ))
                .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_mysql_select_all(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::MySqlPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselMysqlConn,
    n: usize,
) -> Result<(), BoxError> {
    println!("### SELECT ALL (MySQL, {} rows)\n", n);
    print_header();

    sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_mysql(sqlx_pool, n, 100).await?;

    // SZ-ORM (query_values 位置式映射)
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let (cols, rows) = conn
            .query_values("SELECT id, name, email, age FROM bench_users")
            .await?;
        sz_times.push(start.elapsed());
        let _ = (cols.len(), rows.len());
    }
    print_row("sz-orm (values)", &sz_times);

    // SZ-ORM (query_with_params HashMap 映射)
    let mut sz_hash_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let rows = conn
            .query_with_params("SELECT id, name, email, age FROM bench_users", &[])
            .await?;
        sz_hash_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sz-orm (hashmap)", &sz_hash_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let rows = sqlx::query("SELECT id, name, email, age FROM bench_users")
            .fetch_all(sqlx_pool)
            .await?;
        sqlx_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-mysql")]
    {
        let mut diesel_times = Vec::new();
        for _ in 0..TRIALS {
            let start = Instant::now();
            use diesel::sql_types::*;
            #[derive(QueryableByName)]
            struct UserRowAll {
                #[diesel(sql_type = BigInt)]
                id: i64,
                #[diesel(sql_type = Text)]
                name: String,
                #[diesel(sql_type = Text)]
                email: String,
                #[diesel(sql_type = Integer)]
                age: i32,
            }
            let rows: Vec<UserRowAll> = diesel::sql_query("SELECT id, name, email, age FROM bench_users")
                .get_results(diesel_conn)?;
            diesel_times.push(start.elapsed());
            let _ = rows.len();
        }
        print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let rows = sea_db
            .query_all(Statement::from_sql_and_values(
                DatabaseBackend::MySql,
                "SELECT id, name, email, age FROM bench_users",
                vec![],
            ))
            .await?;
        sea_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_mysql_update(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::MySqlPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselMysqlConn,
    prepare_n: usize,
    updates: usize,
) -> Result<(), BoxError> {
    println!(
        "### UPDATE (MySQL, pre-insert {} rows, {} updates)\n",
        prepare_n, updates
    );
    print_header();

    sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_mysql(sqlx_pool, prepare_n, 100).await?;

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "UPDATE bench_users SET name = ? WHERE id = ?",
                &[Value::String("updated_name".to_string()), Value::I64(id)],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            sqlx::query("UPDATE bench_users SET name = ? WHERE id = ?")
                .bind("updated_name")
                .bind(id)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-mysql")]
    {
        let mut diesel_times = Vec::new();
        for _ in 0..TRIALS {
            let start = Instant::now();
            for i in 0..updates {
                let id = (i % prepare_n) as i64 + 1;
                diesel::sql_query("UPDATE bench_users SET name = ? WHERE id = ?")
                    .bind::<diesel::sql_types::Text, _>("updated_name")
                    .bind::<diesel::sql_types::BigInt, _>(id)
                    .execute(diesel_conn)?;
            }
            diesel_times.push(start.elapsed());
        }
        print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::MySql,
                "UPDATE bench_users SET name = ? WHERE id = ?",
                vec!["updated_name".into(), id.into()],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_mysql_delete(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::MySqlPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselMysqlConn,
    n: usize,
) -> Result<(), BoxError> {
    println!("### DELETE {} (MySQL, one-by-one)\n", n);
    print_header();

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_mysql(sqlx_pool, n, 100).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params("DELETE FROM bench_users WHERE id = ?", &[Value::I64(id)])
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_mysql(sqlx_pool, n, 100).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            sqlx::query("DELETE FROM bench_users WHERE id = ?")
                .bind(id)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-mysql")]
    {
        #[cfg(feature = "diesel-mysql")]
        {
            let mut diesel_times = Vec::new();
            for _ in 0..TRIALS {
                diesel::sql_query(MYSQL_TRUNCATE).execute(diesel_conn)?;
                batch_insert_mysql(sqlx_pool, n, 100).await?;
                let start = Instant::now();
                for id in 1..=(n as i64) {
                    diesel::sql_query("DELETE FROM bench_users WHERE id = ?")
                        .bind::<diesel::sql_types::BigInt, _>(id)
                        .execute(diesel_conn)?;
                }
                diesel_times.push(start.elapsed());
            }
            print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");
    }
    #[cfg(not(feature = "diesel-mysql"))]
    print_diesel_skipped("diesel-mysql feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(MYSQL_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_mysql(sqlx_pool, n, 100).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::MySql,
                "DELETE FROM bench_users WHERE id = ?",
                vec![id.into()],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

// ============================================================================
// PostgreSQL benchmark（4 ORM 全对比）
// ============================================================================

async fn ensure_pg_database(url: &str) -> Result<(), BoxError> {
    if let Some(db_start) = url.rfind('/') {
        let db_name = &url[db_start + 1..];
        if !db_name.is_empty() {
            let base_url = format!("{}/postgres", &url[..db_start]);
            let pool = sqlx::postgres::PgPoolOptions::new()
                .max_connections(1)
                .connect(&base_url)
                .await?;
            let exists: bool = sqlx::query_scalar(
                "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = $1)",
            )
            .bind(db_name)
            .fetch_one(&pool)
            .await?;
            if !exists {
                let create_sql = format!("CREATE DATABASE \"{}\"", db_name);
                sqlx::query(sqlx::AssertSqlSafe(&*create_sql)).execute(&pool).await?;
                println!("[setup] PostgreSQL database '{}' created", db_name);
            } else {
                println!("[setup] PostgreSQL database '{}' exists", db_name);
            }
            pool.close().await;
        }
    }
    Ok(())
}

async fn run_pg_bench(url: &str) -> Result<(), BoxError> {
    println!("## PostgreSQL Benchmark\n");
    println!("Connection: `{}`", mask_url(url));
    println!("Rows per scenario: {} (queries: {})\n", REMOTE_ROWS, REMOTE_QUERIES);

    ensure_pg_database(url).await?;

    // SZ-ORM PG
    let sz_handle = Arc::new(PgPoolHandle::connect(url).await?);
    let sz_factory = Arc::new(SqlxPgConnectionFactory::new(sz_handle.clone()));
    let sz_config = PoolConfigBuilder::new().max_size(10).build()?;
    let sz_pool = SzPool::new(sz_config, sz_factory)?;

    // sqlx PG
    let sqlx_pool = sqlx::postgres::PgPoolOptions::new()
        .max_connections(10)
        .connect(url)
        .await?;

    // SeaORM PG
    let mut opt = ConnectOptions::new(url.to_string());
    opt.max_connections(10);
    let sea_db = Database::connect(opt).await?;

    // Diesel PG
    #[cfg(feature = "diesel-postgres")]
    let mut diesel_conn = diesel::pg::PgConnection::establish(url).map_err(|e| -> BoxError {
        format!("diesel pg connect failed: {}", e).into()
    })?;
    #[cfg(not(feature = "diesel-postgres"))]
    let mut diesel_conn: DieselPgConn = ();

    // 创建表
    sqlx::query(PG_CREATE).execute(&sqlx_pool).await?;

    let n = REMOTE_ROWS;
    let queries = REMOTE_QUERIES;

    bench_pg_insert(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;
    bench_pg_select_by_id(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n, queries).await?;
    bench_pg_select_all(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;
    bench_pg_update(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n, queries).await?;
    bench_pg_delete(&sz_pool, &sqlx_pool, &sea_db, &mut diesel_conn, n).await?;

    // 清理
    sqlx::query("DROP TABLE IF EXISTS bench_users").execute(&sqlx_pool).await?;
    sz_pool.close_all().await;
    sqlx_pool.close().await;
    let _ = sea_db.close().await;

    Ok(())
}

async fn bench_pg_insert(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::PgPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselPgConn,
    n: usize,
) -> Result<(), BoxError> {
    println!("### INSERT {} (PostgreSQL)\n", n);
    print_header();

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "INSERT INTO bench_users (name, email, age) VALUES ($1, $2, $3)",
                &[
                    Value::String(format!("user_{}", i)),
                    Value::String(format!("user_{}@test.com", i)),
                    Value::I32((i % 100) as i32),
                ],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            sqlx::query("INSERT INTO bench_users (name, email, age) VALUES ($1, $2, $3)")
                .bind(format!("user_{}", i))
                .bind(format!("user_{}@test.com", i))
                .bind((i % 100) as i32)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-postgres")]
    {
        #[cfg(feature = "diesel-postgres")]
        {
            let mut diesel_times = Vec::new();
            for _ in 0..TRIALS {
                diesel::sql_query(PG_TRUNCATE).execute(diesel_conn)?;
                let start = Instant::now();
                for i in 0..n {
                    diesel::sql_query("INSERT INTO bench_users (name, email, age) VALUES ($1, $2, $3)")
                        .bind::<diesel::sql_types::Text, _>(format!("user_{}", i))
                        .bind::<diesel::sql_types::Text, _>(format!("user_{}@test.com", i))
                        .bind::<diesel::sql_types::Integer, _>((i % 100) as i32)
                        .execute(diesel_conn)?;
                }
                diesel_times.push(start.elapsed());
            }
            print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
        let start = Instant::now();
        for i in 0..n {
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::Postgres,
                "INSERT INTO bench_users (name, email, age) VALUES ($1, $2, $3)",
                vec![
                    format!("user_{}", i).into(),
                    format!("user_{}@test.com", i).into(),
                    ((i % 100) as i32).into(),
                ],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_pg_select_by_id(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::PgPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselPgConn,
    prepare_n: usize,
    queries: usize,
) -> Result<(), BoxError> {
    println!(
        "### SELECT BY ID (PostgreSQL, pre-insert {} rows, {} queries)\n",
        prepare_n, queries
    );
    print_header();

    sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_pg(sqlx_pool, prepare_n, 100).await?;

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            let _rows = conn
                .query_with_params(
                    "SELECT name, email, age FROM bench_users WHERE id = $1",
                    &[Value::I64(id)],
                )
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let _ = sqlx::query("SELECT name, email, age FROM bench_users WHERE id = $1")
                .bind(id)
                .fetch_one(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-postgres")]
    {
        #[cfg(feature = "diesel-postgres")]
        {
            let mut diesel_times = Vec::new();
            for _ in 0..TRIALS {
                let start = Instant::now();
                for i in 0..queries {
                    let id = (i % prepare_n) as i64 + 1;
                    use diesel::sql_types::*;
                    #[derive(QueryableByName)]
                    struct UserRow {
                        #[diesel(sql_type = Text)]
                        name: String,
                        #[diesel(sql_type = Text)]
                        email: String,
                        #[diesel(sql_type = Integer)]
                        age: i32,
                    }
                    let _row: UserRow = diesel::sql_query("SELECT name, email, age FROM bench_users WHERE id = $1")
                        .bind::<BigInt, _>(id)
                        .get_result(diesel_conn)?;
                }
                diesel_times.push(start.elapsed());
            }
            print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let _ = sea_db
                .query_one(Statement::from_sql_and_values(
                    DatabaseBackend::Postgres,
                    "SELECT name, email, age FROM bench_users WHERE id = $1",
                    vec![id.into()],
                ))
                .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_pg_select_all(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::PgPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselPgConn,
    n: usize,
) -> Result<(), BoxError> {
    println!("### SELECT ALL (PostgreSQL, {} rows)\n", n);
    print_header();

    sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_pg(sqlx_pool, n, 100).await?;

    // SZ-ORM (query_values 位置式映射)
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let (cols, rows) = conn
            .query_values("SELECT id, name, email, age FROM bench_users")
            .await?;
        sz_times.push(start.elapsed());
        let _ = (cols.len(), rows.len());
    }
    print_row("sz-orm (values)", &sz_times);

    // SZ-ORM (query_with_params HashMap 映射)
    let mut sz_hash_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let rows = conn
            .query_with_params("SELECT id, name, email, age FROM bench_users", &[])
            .await?;
        sz_hash_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sz-orm (hashmap)", &sz_hash_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let rows = sqlx::query("SELECT id, name, email, age FROM bench_users")
            .fetch_all(sqlx_pool)
            .await?;
        sqlx_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-postgres")]
    {
        let mut diesel_times = Vec::new();
        for _ in 0..TRIALS {
            let start = Instant::now();
            use diesel::sql_types::*;
            #[derive(QueryableByName)]
            struct UserRowAll {
                #[diesel(sql_type = BigInt)]
                id: i64,
                #[diesel(sql_type = Text)]
                name: String,
                #[diesel(sql_type = Text)]
                email: String,
                #[diesel(sql_type = Integer)]
                age: i32,
            }
            let rows: Vec<UserRowAll> = diesel::sql_query("SELECT id, name, email, age FROM bench_users")
                .get_results(diesel_conn)?;
            diesel_times.push(start.elapsed());
            let _ = rows.len();
        }
        print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let rows = sea_db
            .query_all(Statement::from_sql_and_values(
                DatabaseBackend::Postgres,
                "SELECT id, name, email, age FROM bench_users",
                vec![],
            ))
            .await?;
        sea_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_pg_update(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::PgPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselPgConn,
    prepare_n: usize,
    updates: usize,
) -> Result<(), BoxError> {
    println!(
        "### UPDATE (PostgreSQL, pre-insert {} rows, {} updates)\n",
        prepare_n, updates
    );
    print_header();

    sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
    batch_insert_pg(sqlx_pool, prepare_n, 100).await?;

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "UPDATE bench_users SET name = $1 WHERE id = $2",
                &[Value::String("updated_name".to_string()), Value::I64(id)],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            sqlx::query("UPDATE bench_users SET name = $1 WHERE id = $2")
                .bind("updated_name")
                .bind(id)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-postgres")]
    {
        #[cfg(feature = "diesel-postgres")]
        {
            let mut diesel_times = Vec::new();
            for _ in 0..TRIALS {
                let start = Instant::now();
                for i in 0..updates {
                    let id = (i % prepare_n) as i64 + 1;
                    diesel::sql_query("UPDATE bench_users SET name = $1 WHERE id = $2")
                        .bind::<diesel::sql_types::Text, _>("updated_name")
                        .bind::<diesel::sql_types::BigInt, _>(id)
                        .execute(diesel_conn)?;
                }
                diesel_times.push(start.elapsed());
            }
            print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::Postgres,
                "UPDATE bench_users SET name = $1 WHERE id = $2",
                vec!["updated_name".into(), id.into()],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

async fn bench_pg_delete(
    sz_pool: &SzPool,
    sqlx_pool: &sqlx::PgPool,
    sea_db: &DatabaseConnection,
    diesel_conn: &mut DieselPgConn,
    n: usize,
) -> Result<(), BoxError> {
    println!("### DELETE {} (PostgreSQL, one-by-one)\n", n);
    print_header();

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_pg(sqlx_pool, n, 100).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params("DELETE FROM bench_users WHERE id = $1", &[Value::I64(id)])
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // sqlx
    let mut sqlx_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_pg(sqlx_pool, n, 100).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            sqlx::query("DELETE FROM bench_users WHERE id = $1")
                .bind(id)
                .execute(sqlx_pool)
                .await?;
        }
        sqlx_times.push(start.elapsed());
    }
    print_row("sqlx", &sqlx_times);

    // diesel
    #[cfg(feature = "diesel-postgres")]
    {
        #[cfg(feature = "diesel-postgres")]
        {
            let mut diesel_times = Vec::new();
            for _ in 0..TRIALS {
                diesel::sql_query(PG_TRUNCATE).execute(diesel_conn)?;
                batch_insert_pg(sqlx_pool, n, 100).await?;
                let start = Instant::now();
                for id in 1..=(n as i64) {
                    diesel::sql_query("DELETE FROM bench_users WHERE id = $1")
                        .bind::<diesel::sql_types::BigInt, _>(id)
                        .execute(diesel_conn)?;
                }
                diesel_times.push(start.elapsed());
            }
            print_row("diesel", &diesel_times);
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");
    }
    #[cfg(not(feature = "diesel-postgres"))]
    print_diesel_skipped("diesel-postgres feature not enabled");

    // SeaORM
    let mut sea_times = Vec::new();
    for _ in 0..TRIALS {
        sqlx::query(PG_TRUNCATE).execute(sqlx_pool).await?;
        batch_insert_pg(sqlx_pool, n, 100).await?;
        let start = Instant::now();
        for id in 1..=(n as i64) {
            sea_db.execute(Statement::from_sql_and_values(
                DatabaseBackend::Postgres,
                "DELETE FROM bench_users WHERE id = $1",
                vec![id.into()],
            ))
            .await?;
        }
        sea_times.push(start.elapsed());
    }
    print_row("sea-orm", &sea_times);

    println!();
    Ok(())
}

// ============================================================================
// Oracle benchmark（SZ-ORM + raw oracle crate，sqlx/diesel/sea-orm 不支持）
// ============================================================================

/// 解析 Oracle 连接串：user/pass@//host:port/service
#[cfg(feature = "oracle")]
fn parse_oracle_url(url: &str) -> Result<(String, String, String), BoxError> {
    // 期望格式：username/password@//host:port/service
    let at_pos = url.rfind('@').ok_or("invalid oracle url: missing '@'")?;
    let user_pass = &url[..at_pos];
    let connect_string = &url[at_pos + 1..];
    let slash_pos = user_pass.find('/').ok_or("invalid oracle url: missing '/' in user/pass")?;
    let username = user_pass[..slash_pos].to_string();
    let password = user_pass[slash_pos + 1..].to_string();
    Ok((username, password, connect_string.to_string()))
}

#[cfg(feature = "oracle")]
async fn run_oracle_bench(url: &str) -> Result<(), BoxError> {
    println!("## Oracle Benchmark\n");
    println!("Connection: `{}`", mask_url(url));
    println!("Rows per scenario: {} (queries: {})\n", REMOTE_ROWS, REMOTE_QUERIES);

    let (username, password, connect_string) = parse_oracle_url(url)?;

    // SZ-ORM Oracle
    let sz_handle = Arc::new(sz_orm_oracle::OraclePoolHandle::connect(&username, &password, &connect_string)?);
    let sz_factory = Arc::new(sz_orm_oracle::OracleConnectionFactory::new(sz_handle.clone()));
    let sz_config = PoolConfigBuilder::new().max_size(10).build()?;
    let sz_pool = SzPool::new(sz_config, sz_factory)?;

    // 创建表（先 DROP 再 CREATE，因 Oracle 不支持 IF NOT EXISTS）
    {
        let mut conn = sz_pool.acquire().await?;
        let _ = conn.execute(ORACLE_DROP).await; // 忽略不存在错误
        conn.execute(ORACLE_CREATE).await?;
    }

    let n = REMOTE_ROWS;
    let queries = REMOTE_QUERIES;

    bench_oracle_insert(&sz_pool, &username, &password, &connect_string, n).await?;
    bench_oracle_select_by_id(&sz_pool, &username, &password, &connect_string, n, queries).await?;
    bench_oracle_select_all(&sz_pool, &username, &password, &connect_string, n).await?;
    bench_oracle_update(&sz_pool, &username, &password, &connect_string, n, queries).await?;
    bench_oracle_delete(&sz_pool, &username, &password, &connect_string, n).await?;

    // 清理
    {
        let mut conn = sz_pool.acquire().await?;
        let _ = conn.execute(ORACLE_DROP).await;
    }
    sz_pool.close_all().await;

    Ok(())
}

#[cfg(feature = "oracle")]
async fn bench_oracle_insert(
    sz_pool: &SzPool,
    username: &str,
    password: &str,
    connect_string: &str,
    n: usize,
) -> Result<(), BoxError> {
    println!("### INSERT {} (Oracle)\n", n);
    print_header();

    // SZ-ORM（execute_with_params，sz-orm-oracle 自动将 ? 转为 :N）
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        // TRUNCATE 通过 SZ-ORM
        {
            let mut conn = sz_pool.acquire().await?;
            conn.execute(ORACLE_TRUNCATE).await?;
        }
        let start = Instant::now();
        for i in 0..n {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "INSERT INTO bench_users (name, email, age) VALUES (?, ?, ?)",
                &[
                    Value::String(format!("user_{}", i)),
                    Value::String(format!("user_{}@test.com", i)),
                    Value::I32((i % 100) as i32),
                ],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // raw oracle crate（同步，spawn_blocking 包装）
    let mut raw_times = Vec::new();
    for _ in 0..TRIALS {
        let conn = oracle::Connection::connect(username, password, connect_string)
            .map_err(|e| -> BoxError { format!("oracle connect failed: {}", e).into() })?;
        conn.execute(ORACLE_TRUNCATE, &[]).map_err(|e| -> BoxError { e.to_string().into() })?;
        let start = Instant::now();
        for i in 0..n {
            let stmt = conn
                .statement("INSERT INTO bench_users (name, email, age) VALUES (:1, :2, :3)")
                .build()?;
            stmt.execute(
                &[],
                &[
                    &format!("user_{}", i),
                    &format!("user_{}@test.com", i),
                    &(i % 100) as i32,
                ],
            )?;
        }
        raw_times.push(start.elapsed());
        conn.close().ok();
    }
    print_row("raw oracle", &raw_times);

    println!();
    Ok(())
}

#[cfg(feature = "oracle")]
async fn bench_oracle_select_by_id(
    sz_pool: &SzPool,
    username: &str,
    password: &str,
    connect_string: &str,
    prepare_n: usize,
    queries: usize,
) -> Result<(), BoxError> {
    println!(
        "### SELECT BY ID (Oracle, pre-insert {} rows, {} queries)\n",
        prepare_n, queries
    );
    print_header();

    // 预插入数据
    {
        let mut conn = sz_pool.acquire().await?;
        conn.execute(ORACLE_TRUNCATE).await?;
    }
    for chunk_start in (0..prepare_n).step_by(100) {
        let chunk_end = (chunk_start + 100).min(prepare_n);
        let stmt = batch_insert_oracle_stmt(chunk_end - chunk_start, chunk_end - chunk_start);
        // 重写为带偏移的 INSERT ALL
        let mut sql = String::from("INSERT ALL ");
        for i in chunk_start..chunk_end {
            sql.push_str(&format!(
                "INTO bench_users (name, email, age) VALUES ('user_{}', 'user_{}@test.com', {}) ",
                i, i, i % 100
            ));
        }
        sql.push_str("SELECT 1 FROM DUAL");
        let mut conn = sz_pool.acquire().await?;
        conn.execute(&sql).await?;
    }

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            let _rows = conn
                .query_with_params(
                    "SELECT name, email, age FROM bench_users WHERE id = :1",
                    &[Value::I64(id)],
                )
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // raw oracle
    let mut raw_times = Vec::new();
    for _ in 0..TRIALS {
        let conn = oracle::Connection::connect(username, password, connect_string)?;
        let start = Instant::now();
        for i in 0..queries {
            let id = (i % prepare_n) as i64 + 1;
            let stmt = conn
                .statement("SELECT name, email, age FROM bench_users WHERE id = :1")
                .build()?;
            let rows = stmt.query(&[&id])?;
            let _ = rows.count();
        }
        raw_times.push(start.elapsed());
        conn.close().ok();
    }
    print_row("raw oracle", &raw_times);

    println!();
    Ok(())
}

#[cfg(feature = "oracle")]
async fn bench_oracle_select_all(
    sz_pool: &SzPool,
    username: &str,
    password: &str,
    connect_string: &str,
    n: usize,
) -> Result<(), BoxError> {
    println!("### SELECT ALL (Oracle, {} rows)\n", n);
    print_header();

    // 数据已预插入；若 count != n 则补 setup
    {
        let mut conn = sz_pool.acquire().await?;
        let rows = conn.query("SELECT COUNT(*) FROM bench_users").await?;
        let count = rows
            .first()
            .and_then(|r| r.values().next())
            .and_then(|v| v.as_i64())
            .unwrap_or(0);
        if count as usize != n {
            conn.execute(ORACLE_TRUNCATE).await?;
            for chunk_start in (0..n).step_by(100) {
                let chunk_end = (chunk_start + 100).min(n);
                let mut sql = String::from("INSERT ALL ");
                for i in chunk_start..chunk_end {
                    sql.push_str(&format!(
                        "INTO bench_users (name, email, age) VALUES ('user_{}', 'user_{}@test.com', {}) ",
                        i, i, i % 100
                    ));
                }
                sql.push_str("SELECT 1 FROM DUAL");
                conn.execute(&sql).await?;
            }
        }
    }

    // SZ-ORM (query_values 位置式映射)
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let (cols, rows) = conn
            .query_values("SELECT id, name, email, age FROM bench_users")
            .await?;
        sz_times.push(start.elapsed());
        let _ = (cols.len(), rows.len());
    }
    print_row("sz-orm (values)", &sz_times);

    // SZ-ORM (query_with_params HashMap 映射)
    let mut sz_hash_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        let mut conn = sz_pool.acquire().await?;
        let rows = conn
            .query_with_params("SELECT id, name, email, age FROM bench_users", &[])
            .await?;
        sz_hash_times.push(start.elapsed());
        let _ = rows.len();
    }
    print_row("sz-orm (hashmap)", &sz_hash_times);

    // raw oracle
    let mut raw_times = Vec::new();
    for _ in 0..TRIALS {
        let conn = oracle::Connection::connect(username, password, connect_string)?;
        let start = Instant::now();
        let stmt = conn.statement("SELECT id, name, email, age FROM bench_users").build()?;
        let rows = stmt.query(&[])?;
        let count = rows.count();
        raw_times.push(start.elapsed());
        let _ = count;
        conn.close().ok();
    }
    print_row("raw oracle", &raw_times);

    println!();
    Ok(())
}

#[cfg(feature = "oracle")]
async fn bench_oracle_update(
    sz_pool: &SzPool,
    username: &str,
    password: &str,
    connect_string: &str,
    prepare_n: usize,
    updates: usize,
) -> Result<(), BoxError> {
    println!(
        "### UPDATE (Oracle, pre-insert {} rows, {} updates)\n",
        prepare_n, updates
    );
    print_header();

    // 数据已预插入；若 count != prepare_n 则补 setup
    {
        let mut conn = sz_pool.acquire().await?;
        let rows = conn.query("SELECT COUNT(*) FROM bench_users").await?;
        let count = rows
            .first()
            .and_then(|r| r.values().next())
            .and_then(|v| v.as_i64())
            .unwrap_or(0);
        if count as usize != prepare_n {
            conn.execute(ORACLE_TRUNCATE).await?;
            for chunk_start in (0..prepare_n).step_by(100) {
                let chunk_end = (chunk_start + 100).min(prepare_n);
                let mut sql = String::from("INSERT ALL ");
                for i in chunk_start..chunk_end {
                    sql.push_str(&format!(
                        "INTO bench_users (name, email, age) VALUES ('user_{}', 'user_{}@test.com', {}) ",
                        i, i, i % 100
                    ));
                }
                sql.push_str("SELECT 1 FROM DUAL");
                conn.execute(&sql).await?;
            }
        }
    }

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params(
                "UPDATE bench_users SET name = :1 WHERE id = :2",
                &[Value::String("updated_name".to_string()), Value::I64(id)],
            )
            .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // raw oracle
    let mut raw_times = Vec::new();
    for _ in 0..TRIALS {
        let conn = oracle::Connection::connect(username, password, connect_string)?;
        let start = Instant::now();
        for i in 0..updates {
            let id = (i % prepare_n) as i64 + 1;
            let stmt = conn
                .statement("UPDATE bench_users SET name = :1 WHERE id = :2")
                .build()?;
            stmt.execute(&[], &[&"updated_name".to_string(), &id])?;
        }
        raw_times.push(start.elapsed());
        conn.close().ok();
    }
    print_row("raw oracle", &raw_times);

    println!();
    Ok(())
}

#[cfg(feature = "oracle")]
async fn bench_oracle_delete(
    sz_pool: &SzPool,
    username: &str,
    password: &str,
    connect_string: &str,
    n: usize,
) -> Result<(), BoxError> {
    println!("### DELETE {} (Oracle, one-by-one)\n", n);
    print_header();

    // SZ-ORM
    let mut sz_times = Vec::new();
    for _ in 0..TRIALS {
        // 每个 trial 重新插入
        {
            let mut conn = sz_pool.acquire().await?;
            conn.execute(ORACLE_TRUNCATE).await?;
            for chunk_start in (0..n).step_by(100) {
                let chunk_end = (chunk_start + 100).min(n);
                let mut sql = String::from("INSERT ALL ");
                for i in chunk_start..chunk_end {
                    sql.push_str(&format!(
                        "INTO bench_users (name, email, age) VALUES ('user_{}', 'user_{}@test.com', {}) ",
                        i, i, i % 100
                    ));
                }
                sql.push_str("SELECT 1 FROM DUAL");
                conn.execute(&sql).await?;
            }
        }
        let start = Instant::now();
        for id in 1..=(n as i64) {
            let mut conn = sz_pool.acquire().await?;
            conn.execute_with_params("DELETE FROM bench_users WHERE id = :1", &[Value::I64(id)])
                .await?;
        }
        sz_times.push(start.elapsed());
    }
    print_row("sz-orm (params)", &sz_times);

    // raw oracle
    let mut raw_times = Vec::new();
    for _ in 0..TRIALS {
        let conn = oracle::Connection::connect(username, password, connect_string)?;
        conn.execute(ORACLE_TRUNCATE, &[])?;
        for chunk_start in (0..n).step_by(100) {
            let chunk_end = (chunk_start + 100).min(n);
            let mut sql = String::from("INSERT ALL ");
            for i in chunk_start..chunk_end {
                sql.push_str(&format!(
                    "INTO bench_users (name, email, age) VALUES ('user_{}', 'user_{}@test.com', {}) ",
                    i, i, i % 100
                ));
            }
            sql.push_str("SELECT 1 FROM DUAL");
            conn.execute(&sql, &[])?;
        }
        let start = Instant::now();
        for id in 1..=(n as i64) {
            let stmt = conn.statement("DELETE FROM bench_users WHERE id = :1").build()?;
            stmt.execute(&[], &[&id])?;
        }
        raw_times.push(start.elapsed());
        conn.close().ok();
    }
    print_row("raw oracle", &raw_times);

    println!();
    Ok(())
}

// ============================================================================
// main
// ============================================================================

#[tokio::main]
async fn main() -> Result<(), BoxError> {
    let mysql_url = env::var("DATABASE_URL_MYSQL").ok();
    let pg_url = env::var("DATABASE_URL_POSTGRES").ok();
    let oracle_url = env::var("DATABASE_URL_ORACLE").ok();

    println!("# Cross-DB × Cross-ORM Benchmark Results");
    println!();
    println!("Generated: {}", chrono::Local::now().format("%Y-%m-%d %H:%M:%S"));
    println!();
    println!("## Matrix");
    println!();
    println!("| DB          | SZ-ORM | sqlx | diesel | sea-orm | raw oracle |");
    println!("|-------------|:------:|:----:|:------:|:-------:|:----------:|");
    println!("| SQLite      |   ✓    |  ✓   |   ✓    |   ✓     |     -      |");
    println!("| MySQL       |   ✓    |  ✓   |   ✓    |   ✓     |     -      |");
    println!("| PostgreSQL  |   ✓    |  ✓   |   ✓    |   ✓     |     -      |");
    println!("| Oracle      |   ✓    |  -   |   -    |   -     |     ✓      |");
    println!();
    println!("## Scenarios");
    println!();
    println!("- INSERT (SQLite 10K / remote 1K rows, one-by-one)");
    println!("- SELECT BY ID (pre-insert rows, 100/1000 queries)");
    println!("- SELECT ALL (full table scan)");
    println!("- UPDATE (100/1000 single-row updates)");
    println!("- DELETE (one-by-one)");
    println!();
    println!("## SZ-ORM Optimization Paths");
    println!();
    println!("- `execute_with_params`: 真实 prepared statement（INSERT/UPDATE/DELETE）");
    println!("- `query_with_params`: prepared statement + HashMap 行映射（SELECT BY ID）");
    println!("- `query_values`: 位置式映射，绕过 HashMap 开销（SELECT ALL）");
    println!();
    println!("## Env");
    println!();
    println!("- `DATABASE_URL_MYSQL` = `{}`", mysql_url.as_deref().map(mask_url).unwrap_or("(not set, skip)".into()));
    println!("- `DATABASE_URL_POSTGRES` = `{}`", pg_url.as_deref().map(mask_url).unwrap_or("(not set, skip)".into()));
    println!("- `DATABASE_URL_ORACLE` = `{}`", oracle_url.as_deref().map(mask_url).unwrap_or("(not set, skip)".into()));
    println!();
    println!("Pool: max_connections=10 (all ORMs)");
    println!("Trials per scenario: {} (median reported)", TRIALS);
    println!();

    // SQLite（始终运行）
    println!("\n--- SQLite benchmark start ---\n");
    run_sqlite_bench().await?;
    println!("--- SQLite benchmark end ---\n");

    // MySQL
    if let Some(url) = &mysql_url {
        println!("\n--- MySQL benchmark start ---\n");
        run_mysql_bench(url).await?;
        println!("--- MySQL benchmark end ---\n");
    }

    // PostgreSQL
    if let Some(url) = &pg_url {
        println!("\n--- PostgreSQL benchmark start ---\n");
        run_pg_bench(url).await?;
        println!("--- PostgreSQL benchmark end ---\n");
    }

    // Oracle
    #[cfg(feature = "oracle")]
    if let Some(url) = &oracle_url {
        println!("\n--- Oracle benchmark start ---\n");
        run_oracle_bench(url).await?;
        println!("--- Oracle benchmark end ---\n");
    }
    #[cfg(not(feature = "oracle"))]
    if oracle_url.is_some() {
        println!("\n--- Oracle benchmark skipped (oracle feature not enabled) ---\n");
    }

    Ok(())
}
