#!/usr/bin/env python3
"""rustdoc 注释自动翻译脚本

用术语对照表 + 常见模式匹配，自动翻译 /// 注释中的中文为英文。
对于无法自动翻译的行，保留原文并输出统计。
用法：python scripts/translate-rustdoc.py
"""

import re
import sys
from pathlib import Path

TERM_MAP = {
    "连接池": "connection pool",
    "连接池耗尽": "pool exhaustion",
    "连接泄漏": "connection leak",
    "预热": "prewarm",
    "获取": "acquire",
    "释放": "release",
    "方言": "dialect",
    "查询构造器": "query builder",
    "派生宏": "derive macro",
    "过程宏": "procedural macro",
    "模型": "model",
    "事务": "transaction",
    "迁移": "migration",
    "钩子": "hook",
    "软删除": "soft delete",
    "多租户": "multi-tenant",
    "行级安全": "row-level security",
    "列级脱敏": "column masking",
    "分片": "sharding",
    "读写分离": "read-write splitting",
    "主从切换": "primary-standby failover",
    "脑裂": "split-brain",
    "工作空间": "workspace",
    "异步": "asynchronous",
    "运行时": "runtime",
    "参数化查询": "parameterized query",
    "SQL 注入": "SQL injection",
    "零拷贝": "zero-copy",
    "内联存储": "inline storage",
    "类型安全": "type-safe",
    "悲观锁": "pessimistic lock",
    "共享锁": "shared lock",
    "行锁": "row lock",
    "查询缓存": "query cache",
    "缓存一致性": "cache coherence",
    "击穿": "cache penetration",
    "雪崩": "cache stampede",
    "失效": "invalidation",
    "写穿透": "write-through",
    "写后": "write-behind",
    "可观测性": "observability",
    "审计": "audit",
    "指标采集": "metric collection",
    "滑动窗口": "sliding window",
    "基线": "baseline",
    "突增": "spike",
    "突增检测": "spike detection",
    "异常检测": "anomaly detection",
    "告警去重": "alert deduplication",
    "消息轨迹": "message tracing",
    "存储生命周期": "storage lifecycle",
    "数据质量": "data quality",
    "批量流式": "batch streaming",
    "备份验证": "backup verification",
    "数据 lineage": "data lineage",
    "变更数据捕获": "Change Data Capture",
    "服务网格": "service mesh",
    "基准": "benchmark",
    "火焰图": "flamegraph",
    "慢查询诊断": "slow query diagnosis",
    "自适应查询": "adaptive query",
    "混合搜索": "hybrid search",
    "向量搜索": "vector search",
    "全文搜索": "full-text search",
    "自动调优": "auto-tuning",
    "自动故障转移": "auto failover",
    "索引建议": "index advice",
    "查询重写": "query rewrite",
    "意图分析": "intent analysis",
    "特性门控": "feature gate",
    "生产就绪": "production ready",
    "竞品": "competitor",
    "成熟度": "maturity",
    "路线图": "roadmap",
    "交付": "delivery",
    "文档测试": "doctest",
    "安全审计": "security audit",
    "覆盖率": "coverage",
    "变异测试": "mutation testing",
    "幻影交付": "phantom delivery",
    "占位实现": "placeholder implementation",
    "信创": "domestic computing",
    "鲜视达": "Xianshida",
}

SENTENCE_MAP = {
    "构造": "Construct",
    "创建": "Create",
    "返回": "Returns",
    "获取": "Get",
    "设置": "Set",
    "检查": "Check",
    "验证": "Validate",
    "执行": "Execute",
    "应用": "Apply",
    "生成": "Generate",
    "解析": "Parse",
    "转换": "Convert",
    "比较": "Compare",
    "计算": "Calculate",
    "初始化": "Initialize",
    "配置": "Configure",
    "注册": "Register",
    "注销": "Deregister",
    "启用": "Enable",
    "禁用": "Disable",
    "添加": "Add",
    "删除": "Delete",
    "更新": "Update",
    "查询": "Query",
    "插入": "Insert",
    "提交": "Commit",
    "回滚": "Rollback",
    "开始": "Start",
    "结束": "End",
    "打开": "Open",
    "关闭": "Close",
    "读取": "Read",
    "写入": "Write",
    "加载": "Load",
    "保存": "Save",
    "刷新": "Refresh",
    "重置": "Reset",
    "清空": "Clear",
    "复制": "Clone",
    "拷贝": "Copy",
    "移动": "Move",
    "替换": "Replace",
    "查找": "Find",
    "搜索": "Search",
    "排序": "Sort",
    "分组": "Group",
    "过滤": "Filter",
    "跳过": "Skip",
    "限制": "Limit",
    "偏移": "Offset",
    "分页": "Paginate",
    "连接": "Connect",
    "断开": "Disconnect",
    "发送": "Send",
    "接收": "Receive",
    "推送": "Push",
    "拉取": "Pull",
    "订阅": "Subscribe",
    "发布": "Publish",
    "等待": "Wait",
    "唤醒": "Wake",
    "通知": "Notify",
    "触发": "Trigger",
    "调度": "Schedule",
    "延迟": "Delay",
    "超时": "Timeout",
    "重试": "Retry",
    "取消": "Cancel",
    "中断": "Interrupt",
    "暂停": "Pause",
    "恢复": "Resume",
    "停止": "Stop",
    "启动": "Start",
    "运行": "Run",
    "测试": "Test",
    "调试": "Debug",
    "日志": "Log",
    "警告": "Warn",
    "错误": "Error",
    "异常": "Exception",
    "成功": "Success",
    "失败": "Fail",
    "通过": "Pass",
    "跳过": "Skip",
    "忽略": "Ignore",
    "支持": "Support",
    "不支持": "Not supported",
    "已弃用": "Deprecated",
    "已移除": "Removed",
    "已修复": "Fixed",
    "已知": "Known",
    "未知": "Unknown",
    "默认": "Default",
    "可选": "Optional",
    "必填": "Required",
    "空": "Empty",
    "非空": "Non-empty",
    "有效": "Valid",
    "无效": "Invalid",
    "允许": "Allow",
    "拒绝": "Deny",
    "许可": "Permit",
    "禁止": "Forbid",
    "限制": "Restrict",
    "约束": "Constraint",
    "规则": "Rule",
    "策略": "Strategy",
    "模式": "Pattern",
    "类型": "Type",
    "种类": "Kind",
    "变体": "Variant",
    "字段": "Field",
    "列": "Column",
    "行": "Row",
    "表": "Table",
    "索引": "Index",
    "键": "Key",
    "值": "Value",
    "属性": "Attribute",
    "方法": "Method",
    "函数": "Function",
    "结构体": "Struct",
    "枚举": "Enum",
    " trait": " trait",
    "模块": "Module",
    "包": "Package",
    " crate": " crate",
    "示例": "Example",
    "参数": "Parameter",
    "返回值": "Return value",
    "错误码": "Error code",
    "状态码": "Status code",
    "上下文": "Context",
    "会话": "Session",
    "请求": "Request",
    "响应": "Response",
    "标头": "Header",
    "主体": "Body",
    "载荷": "Payload",
    "元数据": "Metadata",
    "标签": "Label",
    "标记": "Mark",
    "标志": "Flag",
    "选项": "Option",
    "配置": "Config",
    "设定": "Setting",
    "偏好": "Preference",
    "主题": "Topic",
    "队列": "Queue",
    "栈": "Stack",
    "堆": "Heap",
    "池": "Pool",
    "缓冲区": "Buffer",
    "缓存": "Cache",
    "存储": "Storage",
    "磁盘": "Disk",
    "内存": "Memory",
    "网络": "Network",
    "端口": "Port",
    "地址": "Address",
    "主机": "Host",
    "域名": "Domain",
    "协议": "Protocol",
    "版本": "Version",
    "编号": "ID",
    "标识符": "Identifier",
    "名称": "Name",
    "描述": "Description",
    "备注": "Note",
    "警告": "Warning",
    "注意": "Note",
    "提示": "Hint",
    "说明": "Explanation",
    "注释": "Comment",
    "文档": "Documentation",
    "链接": "Link",
    "引用": "Reference",
    "来源": "Source",
    "目标": "Target",
    "源": "Source",
    "结果": "Result",
    "输出": "Output",
    "输入": "Input",
    "前缀": "Prefix",
    "后缀": "Suffix",
    "分隔符": "Separator",
    "占位符": "Placeholder",
    "模板": "Template",
    "格式": "Format",
    "编码": "Encoding",
    "解码": "Decoding",
    "加密": "Encryption",
    "解密": "Decryption",
    "签名": "Signature",
    "证书": "Certificate",
    "密钥": "Key",
    "密码": "Password",
    "令牌": "Token",
    "凭据": "Credential",
    "授权": "Authorization",
    "认证": "Authentication",
    "权限": "Permission",
    "角色": "Role",
    "用户": "User",
    "租户": "Tenant",
    "管理员": "Admin",
    "客户端": "Client",
    "服务端": "Server",
    "代理": "Proxy",
    "网关": "Gateway",
    "路由": "Route",
    "端点": "Endpoint",
    "接口": "Interface",
    "实现": "Implementation",
    "抽象": "Abstraction",
    "封装": "Encapsulation",
    "继承": "Inheritance",
    "组合": "Composition",
    "聚合": "Aggregation",
    "关联": "Association",
    "依赖": "Dependency",
    "耦合": "Coupling",
    "内聚": "Cohesion",
    "分层": "Layering",
    "架构": "Architecture",
    "设计": "Design",
    "模式": "Pattern",
    "原则": "Principle",
    "约定": "Convention",
    "规范": "Specification",
    "标准": "Standard",
    "兼容": "Compatible",
    "不兼容": "Incompatible",
    "向后兼容": "Backward compatible",
    "向前兼容": "Forward compatible",
    "破坏性变更": "Breaking change",
    "非破坏性变更": "Non-breaking change",
    "弃用": "Deprecate",
    "移除": "Remove",
    "新增": "Add",
    "修改": "Modify",
    "重构": "Refactor",
    "优化": "Optimize",
    "简化": "Simplify",
    "改进": "Improve",
    "增强": "Enhance",
    "扩展": "Extend",
    "继承": "Inherit",
    "覆写": "Override",
    "重载": "Overload",
    "多态": "Polymorphism",
    "泛型": "Generic",
    " trait": " trait",
    "生命周期": "Lifetime",
    "所有权": "Ownership",
    "借用": "Borrow",
    "引用计数": "Reference count",
    "智能指针": "Smart pointer",
    "垃圾回收": "Garbage collection",
    "内存安全": "Memory safety",
    "线程安全": "Thread safety",
    "并发": "Concurrency",
    "并行": "Parallelism",
    "同步": "Synchronous",
    "锁": "Lock",
    "互斥": "Mutex",
    "信号量": "Semaphore",
    "条件变量": "Condition variable",
    "原子": "Atomic",
    "无锁": "Lock-free",
    "非阻塞": "Non-blocking",
    "阻塞": "Blocking",
    "回调": "Callback",
    " future": " future",
    "流": "Stream",
    "通道": "Channel",
    "任务": "Task",
    "线程": "Thread",
    "进程": "Process",
    "协程": "Coroutine",
    "生成器": "Generator",
    "迭代器": "Iterator",
    "收集器": "Collector",
    "映射": "Map",
    "过滤": "Filter",
    "归约": "Reduce",
    "折叠": "Fold",
    "扫描": "Scan",
    "跳过": "Skip",
    "取": "Take",
    "丢弃": "Drop",
    "链": "Chain",
    "压缩": "Zip",
    "枚举": "Enumerate",
    "反转": "Reverse",
    "去重": "Dedup",
    "排序": "Sort",
    "最小": "Min",
    "最大": "Max",
    "求和": "Sum",
    "平均": "Avg",
    "计数": "Count",
    "存在": "Exists",
    "任意": "Any",
    "所有": "All",
    "第一个": "First",
    "最后一个": "Last",
    "下一个": "Next",
    "前一个": "Prev",
    "空": "Empty",
    "长度": "Length",
    "大小": "Size",
    "容量": "Capacity",
    "剩余": "Remaining",
    "可用": "Available",
    "已用": "Used",
    "空闲": "Idle",
    "活跃": "Active",
    "等待中": "Waiting",
    "运行中": "Running",
    "已完成": "Completed",
    "已取消": "Cancelled",
    "已失败": "Failed",
    "已超时": "Timed out",
    "已关闭": "Closed",
    "已打开": "Opened",
    "已连接": "Connected",
    "已断开": "Disconnected",
    "已注册": "Registered",
    "已注销": "Deregistered",
    "已启用": "Enabled",
    "已禁用": "Disabled",
    "已锁定": "Locked",
    "已解锁": "Unlocked",
    "已过期": "Expired",
    "已刷新": "Refreshed",
    "已重置": "Reset",
    "已清空": "Cleared",
    "已加载": "Loaded",
    "已保存": "Saved",
    "已提交": "Committed",
    "已回滚": "Rolled back",
    "已应用": "Applied",
    "已撤销": "Reverted",
    "已跳过": "Skipped",
    "已忽略": "Ignored",
    "已匹配": "Matched",
    "未匹配": "Not matched",
    "已找到": "Found",
    "未找到": "Not found",
    "已存在": "Exists",
    "不存在": "Not exists",
    "已创建": "Created",
    "已删除": "Deleted",
    "已更新": "Updated",
    "已插入": "Inserted",
    "已替换": "Replaced",
    "已合并": "Merged",
    "已拆分": "Split",
    "已复制": "Copied",
    "已移动": "Moved",
    "已发送": "Sent",
    "已接收": "Received",
    "已推送": "Pushed",
    "已拉取": "Pulled",
    "已发布": "Published",
    "已订阅": "Subscribed",
    "已通知": "Notified",
    "已触发": "Triggered",
    "已调度": "Scheduled",
    "已执行": "Executed",
    "已处理": "Processed",
    "已解析": "Parsed",
    "已转换": "Converted",
    "已格式化": "Formatted",
    "已编码": "Encoded",
    "已解码": "Decoded",
    "已加密": "Encrypted",
    "已解密": "Decrypted",
    "已签名": "Signed",
    "已验证": "Verified",
    "已确认": "Confirmed",
    "已拒绝": "Rejected",
    "已批准": "Approved",
    "已审核": "Reviewed",
    "已审计": "Audited",
    "已记录": "Logged",
    "已跟踪": "Tracked",
    "已监控": "Monitored",
    "已报警": "Alerted",
    "已报告": "Reported",
    "已统计": "Counted",
    "已分析": "Analyzed",
    "已评估": "Evaluated",
    "已测试": "Tested",
    "已基准": "Benchmarked",
    "已优化": "Optimized",
    "已简化": "Simplified",
    "已改进": "Improved",
    "已增强": "Enhanced",
    "已扩展": "Extended",
    "已重构": "Refactored",
    "已修复": "Fixed",
    "已解决": "Resolved",
    "已完成": "Done",
    "进行中": "In progress",
    "待处理": "Pending",
    "已就绪": "Ready",
    "未就绪": "Not ready",
    "已初始化": "Initialized",
    "已配置": "Configured",
    "已安装": "Installed",
    "已卸载": "Uninstalled",
    "已部署": "Deployed",
    "已回滚": "Rolled back",
    "已迁移": "Migrated",
    "已升级": "Upgraded",
    "已降级": "Downgraded",
    "已启动": "Started",
    "已停止": "Stopped",
    "已暂停": "Paused",
    "已恢复": "Resumed",
    "已重试": "Retried",
    "已取消": "Cancelled",
    "已中断": "Interrupted",
    "已超时": "Timed out",
    "已过期": "Expired",
    "已淘汰": "Evicted",
    "已回收": "Reaped",
    "已清理": "Cleaned",
    "已压缩": "Compressed",
    "已解压": "Decompressed",
    "已打包": "Packaged",
    "已解包": "Unpackaged",
    "已序列化": "Serialized",
    "已反序列化": "Deserialized",
    "已校验": "Checksummed",
    "已摘要": "Digested",
    "已哈希": "Hashed",
    "已签名": "Signed",
    "已加密": "Encrypted",
    "已脱敏": "Desensitized",
    "已掩码": "Masked",
    "已过滤": "Filtered",
    "已脱敏": "Desensitized",
    "已脱敏": "Sanitized",
}

COMMON_PATTERNS = [
    (r"///\s*获取", "/// Get"),
    (r"///\s*设置", "/// Set"),
    (r"///\s*创建", "/// Create"),
    (r"///\s*返回", "/// Returns"),
    (r"///\s*检查", "/// Check"),
    (r"///\s*验证", "/// Validate"),
    (r"///\s*执行", "/// Execute"),
    (r"///\s*应用", "/// Apply"),
    (r"///\s*生成", "/// Generate"),
    (r"///\s*解析", "/// Parse"),
    (r"///\s*转换", "/// Convert"),
    (r"///\s*初始化", "/// Initialize"),
    (r"///\s*配置", "/// Configure"),
    (r"///\s*注册", "/// Register"),
    (r"///\s*启用", "/// Enable"),
    (r"///\s*禁用", "/// Disable"),
    (r"///\s*添加", "/// Add"),
    (r"///\s*删除", "/// Delete"),
    (r"///\s*更新", "/// Update"),
    (r"///\s*查询", "/// Query"),
    (r"///\s*插入", "/// Insert"),
    (r"///\s*提交", "/// Commit"),
    (r"///\s*回滚", "/// Rollback"),
    (r"///\s*读取", "/// Read"),
    (r"///\s*写入", "/// Write"),
    (r"///\s*加载", "/// Load"),
    (r"///\s*保存", "/// Save"),
    (r"///\s*刷新", "/// Refresh"),
    (r"///\s*重置", "/// Reset"),
    (r"///\s*清空", "/// Clear"),
    (r"///\s*复制", "/// Clone"),
    (r"///\s*替换", "/// Replace"),
    (r"///\s*查找", "/// Find"),
    (r"///\s*搜索", "/// Search"),
    (r"///\s*排序", "/// Sort"),
    (r"///\s*过滤", "/// Filter"),
    (r"///\s*限制", "/// Limit"),
    (r"///\s*分页", "/// Paginate"),
    (r"///\s*连接", "/// Connect"),
    (r"///\s*断开", "/// Disconnect"),
    (r"///\s*发送", "/// Send"),
    (r"///\s*接收", "/// Receive"),
    (r"///\s*推送", "/// Push"),
    (r"///\s*拉取", "/// Pull"),
    (r"///\s*订阅", "/// Subscribe"),
    (r"///\s*发布", "/// Publish"),
    (r"///\s*等待", "/// Wait"),
    (r"///\s*通知", "/// Notify"),
    (r"///\s*触发", "/// Trigger"),
    (r"///\s*调度", "/// Schedule"),
    (r"///\s*超时", "/// Timeout"),
    (r"///\s*重试", "/// Retry"),
    (r"///\s*取消", "/// Cancel"),
    (r"///\s*暂停", "/// Pause"),
    (r"///\s*恢复", "/// Resume"),
    (r"///\s*停止", "/// Stop"),
    (r"///\s*启动", "/// Start"),
    (r"///\s*运行", "/// Run"),
    (r"///\s*测试", "/// Test"),
    (r"///\s*日志", "/// Log"),
    (r"///\s*警告", "/// Warning"),
    (r"///\s*错误", "/// Error"),
    (r"///\s*异常", "/// Exception"),
    (r"///\s*成功", "/// Success"),
    (r"///\s*失败", "/// Fail"),
    (r"///\s*通过", "/// Pass"),
    (r"///\s*跳过", "/// Skip"),
    (r"///\s*忽略", "/// Ignore"),
    (r"///\s*支持", "/// Support"),
    (r"///\s*不支持", "/// Not supported"),
    (r"///\s*已弃用", "/// Deprecated"),
    (r"///\s*已移除", "/// Removed"),
    (r"///\s*已修复", "/// Fixed"),
    (r"///\s*默认", "/// Default"),
    (r"///\s*可选", "/// Optional"),
    (r"///\s*必填", "/// Required"),
    (r"///\s*空", "/// Empty"),
    (r"///\s*非空", "/// Non-empty"),
    (r"///\s*有效", "/// Valid"),
    (r"///\s*无效", "/// Invalid"),
    (r"///\s*允许", "/// Allow"),
    (r"///\s*拒绝", "/// Deny"),
    (r"///\s*禁止", "/// Forbid"),
    (r"///\s*限制", "/// Restrict"),
    (r"///\s*约束", "/// Constraint"),
    (r"///\s*规则", "/// Rule"),
    (r"///\s*策略", "/// Strategy"),
    (r"///\s*模式", "/// Pattern"),
    (r"///\s*类型", "/// Type"),
    (r"///\s*字段", "/// Field"),
    (r"///\s*列", "/// Column"),
    (r"///\s*行", "/// Row"),
    (r"///\s*表", "/// Table"),
    (r"///\s*索引", "/// Index"),
    (r"///\s*键", "/// Key"),
    (r"///\s*值", "/// Value"),
    (r"///\s*属性", "/// Attribute"),
    (r"///\s*方法", "/// Method"),
    (r"///\s*函数", "/// Function"),
    (r"///\s*结构体", "/// Struct"),
    (r"///\s*枚举", "/// Enum"),
    (r"///\s*模块", "/// Module"),
    (r"///\s*包", "/// Package"),
    (r"///\s*示例", "/// Example"),
    (r"///\s*参数", "/// Parameter"),
    (r"///\s*返回值", "/// Return value"),
    (r"///\s*错误码", "/// Error code"),
    (r"///\s*状态码", "/// Status code"),
    (r"///\s*上下文", "/// Context"),
    (r"///\s*会话", "/// Session"),
    (r"///\s*请求", "/// Request"),
    (r"///\s*响应", "/// Response"),
    (r"///\s*标头", "/// Header"),
    (r"///\s*主体", "/// Body"),
    (r"///\s*载荷", "/// Payload"),
    (r"///\s*元数据", "/// Metadata"),
    (r"///\s*标签", "/// Label"),
    (r"///\s*标记", "/// Mark"),
    (r"///\s*标志", "/// Flag"),
    (r"///\s*选项", "/// Option"),
    (r"///\s*配置", "/// Config"),
    (r"///\s*主题", "/// Topic"),
    (r"///\s*队列", "/// Queue"),
    (r"///\s*栈", "/// Stack"),
    (r"///\s*堆", "/// Heap"),
    (r"///\s*池", "/// Pool"),
    (r"///\s*缓冲区", "/// Buffer"),
    (r"///\s*缓存", "/// Cache"),
    (r"///\s*存储", "/// Storage"),
    (r"///\s*磁盘", "/// Disk"),
    (r"///\s*内存", "/// Memory"),
    (r"///\s*网络", "/// Network"),
    (r"///\s*端口", "/// Port"),
    (r"///\s*地址", "/// Address"),
    (r"///\s*主机", "/// Host"),
    (r"///\s*域名", "/// Domain"),
    (r"///\s*协议", "/// Protocol"),
    (r"///\s*版本", "/// Version"),
    (r"///\s*编号", "/// ID"),
    (r"///\s*标识符", "/// Identifier"),
    (r"///\s*名称", "/// Name"),
    (r"///\s*描述", "/// Description"),
    (r"///\s*备注", "/// Note"),
    (r"///\s*注意", "/// Note"),
    (r"///\s*提示", "/// Hint"),
    (r"///\s*说明", "/// Explanation"),
    (r"///\s*注释", "/// Comment"),
    (r"///\s*文档", "/// Documentation"),
    (r"///\s*链接", "/// Link"),
    (r"///\s*引用", "/// Reference"),
    (r"///\s*来源", "/// Source"),
    (r"///\s*目标", "/// Target"),
    (r"///\s*源", "/// Source"),
    (r"///\s*结果", "/// Result"),
    (r"///\s*输出", "/// Output"),
    (r"///\s*输入", "/// Input"),
    (r"///\s*前缀", "/// Prefix"),
    (r"///\s*后缀", "/// Suffix"),
    (r"///\s*分隔符", "/// Separator"),
    (r"///\s*占位符", "/// Placeholder"),
    (r"///\s*模板", "/// Template"),
    (r"///\s*格式", "/// Format"),
    (r"///\s*编码", "/// Encoding"),
    (r"///\s*解码", "/// Decoding"),
    (r"///\s*加密", "/// Encryption"),
    (r"///\s*解密", "/// Decryption"),
    (r"///\s*签名", "/// Signature"),
    (r"///\s*证书", "/// Certificate"),
    (r"///\s*密钥", "/// Key"),
    (r"///\s*密码", "/// Password"),
    (r"///\s*令牌", "/// Token"),
    (r"///\s*凭据", "/// Credential"),
    (r"///\s*授权", "/// Authorization"),
    (r"///\s*认证", "/// Authentication"),
    (r"///\s*权限", "/// Permission"),
    (r"///\s*角色", "/// Role"),
    (r"///\s*用户", "/// User"),
    (r"///\s*租户", "/// Tenant"),
    (r"///\s*管理员", "/// Admin"),
    (r"///\s*客户端", "/// Client"),
    (r"///\s*服务端", "/// Server"),
    (r"///\s*代理", "/// Proxy"),
    (r"///\s*网关", "/// Gateway"),
    (r"///\s*路由", "/// Route"),
    (r"///\s*端点", "/// Endpoint"),
    (r"///\s*接口", "/// Interface"),
    (r"///\s*实现", "/// Implementation"),
    (r"///\s*抽象", "/// Abstraction"),
    (r"///\s*封装", "/// Encapsulation"),
    (r"///\s*继承", "/// Inheritance"),
    (r"///\s*组合", "/// Composition"),
    (r"///\s*聚合", "/// Aggregation"),
    (r"///\s*关联", "/// Association"),
    (r"///\s*依赖", "/// Dependency"),
    (r"///\s*耦合", "/// Coupling"),
    (r"///\s*内聚", "/// Cohesion"),
    (r"///\s*分层", "/// Layering"),
    (r"///\s*架构", "/// Architecture"),
    (r"///\s*设计", "/// Design"),
    (r"///\s*原则", "/// Principle"),
    (r"///\s*约定", "/// Convention"),
    (r"///\s*规范", "/// Specification"),
    (r"///\s*标准", "/// Standard"),
    (r"///\s*兼容", "/// Compatible"),
    (r"///\s*不兼容", "/// Incompatible"),
    (r"///\s*向后兼容", "/// Backward compatible"),
    (r"///\s*向前兼容", "/// Forward compatible"),
    (r"///\s*破坏性变更", "/// Breaking change"),
    (r"///\s*非破坏性变更", "/// Non-breaking change"),
    (r"///\s*弃用", "/// Deprecate"),
    (r"///\s*移除", "/// Remove"),
    (r"///\s*新增", "/// Add"),
    (r"///\s*修改", "/// Modify"),
    (r"///\s*重构", "/// Refactor"),
    (r"///\s*优化", "/// Optimize"),
    (r"///\s*简化", "/// Simplify"),
    (r"///\s*改进", "/// Improve"),
    (r"///\s*增强", "/// Enhance"),
    (r"///\s*扩展", "/// Extend"),
    (r"///\s*覆写", "/// Override"),
    (r"///\s*重载", "/// Overload"),
    (r"///\s*多态", "/// Polymorphism"),
    (r"///\s*泛型", "/// Generic"),
    (r"///\s*生命周期", "/// Lifetime"),
    (r"///\s*所有权", "/// Ownership"),
    (r"///\s*借用", "/// Borrow"),
    (r"///\s*引用计数", "/// Reference count"),
    (r"///\s*智能指针", "/// Smart pointer"),
    (r"///\s*垃圾回收", "/// Garbage collection"),
    (r"///\s*内存安全", "/// Memory safety"),
    (r"///\s*线程安全", "/// Thread safety"),
    (r"///\s*并发", "/// Concurrency"),
    (r"///\s*并行", "/// Parallelism"),
    (r"///\s*同步", "/// Synchronous"),
    (r"///\s*锁", "/// Lock"),
    (r"///\s*互斥", "/// Mutex"),
    (r"///\s*信号量", "/// Semaphore"),
    (r"///\s*条件变量", "/// Condition variable"),
    (r"///\s*原子", "/// Atomic"),
    (r"///\s*无锁", "/// Lock-free"),
    (r"///\s*非阻塞", "/// Non-blocking"),
    (r"///\s*阻塞", "/// Blocking"),
    (r"///\s*回调", "/// Callback"),
    (r"///\s*流", "/// Stream"),
    (r"///\s*通道", "/// Channel"),
    (r"///\s*任务", "/// Task"),
    (r"///\s*线程", "/// Thread"),
    (r"///\s*进程", "/// Process"),
    (r"///\s*协程", "/// Coroutine"),
    (r"///\s*生成器", "/// Generator"),
    (r"///\s*迭代器", "/// Iterator"),
    (r"///\s*收集器", "/// Collector"),
    (r"///\s*映射", "/// Map"),
    (r"///\s*归约", "/// Reduce"),
    (r"///\s*折叠", "/// Fold"),
    (r"///\s*去重", "/// Dedup"),
    (r"///\s*最小", "/// Min"),
    (r"///\s*最大", "/// Max"),
    (r"///\s*求和", "/// Sum"),
    (r"///\s*平均", "/// Avg"),
    (r"///\s*计数", "/// Count"),
    (r"///\s*存在", "/// Exists"),
    (r"///\s*任意", "/// Any"),
    (r"///\s*所有", "/// All"),
    (r"///\s*第一个", "/// First"),
    (r"///\s*最后一个", "/// Last"),
    (r"///\s*下一个", "/// Next"),
    (r"///\s*前一个", "/// Prev"),
    (r"///\s*长度", "/// Length"),
    (r"///\s*大小", "/// Size"),
    (r"///\s*容量", "/// Capacity"),
    (r"///\s*剩余", "/// Remaining"),
    (r"///\s*可用", "/// Available"),
    (r"///\s*已用", "/// Used"),
    (r"///\s*空闲", "/// Idle"),
    (r"///\s*活跃", "/// Active"),
    (r"///\s*等待中", "/// Waiting"),
    (r"///\s*运行中", "/// Running"),
    (r"///\s*已完成", "/// Completed"),
    (r"///\s*已取消", "/// Cancelled"),
    (r"///\s*已失败", "/// Failed"),
    (r"///\s*已超时", "/// Timed out"),
    (r"///\s*已关闭", "/// Closed"),
    (r"///\s*已打开", "/// Opened"),
    (r"///\s*已连接", "/// Connected"),
    (r"///\s*已断开", "/// Disconnected"),
    (r"///\s*已注册", "/// Registered"),
    (r"///\s*已启用", "/// Enabled"),
    (r"///\s*已禁用", "/// Disabled"),
    (r"///\s*已锁定", "/// Locked"),
    (r"///\s*已解锁", "/// Unlocked"),
    (r"///\s*已过期", "/// Expired"),
    (r"///\s*已刷新", "/// Refreshed"),
    (r"///\s*已重置", "/// Reset"),
    (r"///\s*已清空", "/// Cleared"),
    (r"///\s*已加载", "/// Loaded"),
    (r"///\s*已保存", "/// Saved"),
    (r"///\s*已提交", "/// Committed"),
    (r"///\s*已回滚", "/// Rolled back"),
    (r"///\s*已应用", "/// Applied"),
    (r"///\s*已跳过", "/// Skipped"),
    (r"///\s*已忽略", "/// Ignored"),
    (r"///\s*已匹配", "/// Matched"),
    (r"///\s*未匹配", "/// Not matched"),
    (r"///\s*已找到", "/// Found"),
    (r"///\s*未找到", "/// Not found"),
    (r"///\s*已存在", "/// Exists"),
    (r"///\s*不存在", "/// Not exists"),
    (r"///\s*已创建", "/// Created"),
    (r"///\s*已删除", "/// Deleted"),
    (r"///\s*已更新", "/// Updated"),
    (r"///\s*已插入", "/// Inserted"),
    (r"///\s*已替换", "/// Replaced"),
    (r"///\s*已合并", "/// Merged"),
    (r"///\s*已拆分", "/// Split"),
    (r"///\s*已移动", "/// Moved"),
    (r"///\s*已发送", "/// Sent"),
    (r"///\s*已接收", "/// Received"),
    (r"///\s*已推送", "/// Pushed"),
    (r"///\s*已拉取", "/// Pulled"),
    (r"///\s*已发布", "/// Published"),
    (r"///\s*已订阅", "/// Subscribed"),
    (r"///\s*已通知", "/// Notified"),
    (r"///\s*已触发", "/// Triggered"),
    (r"///\s*已调度", "/// Scheduled"),
    (r"///\s*已执行", "/// Executed"),
    (r"///\s*已处理", "/// Processed"),
    (r"///\s*已解析", "/// Parsed"),
    (r"///\s*已转换", "/// Converted"),
    (r"///\s*已格式化", "/// Formatted"),
    (r"///\s*已编码", "/// Encoded"),
    (r"///\s*已解码", "/// Decoded"),
    (r"///\s*已加密", "/// Encrypted"),
    (r"///\s*已解密", "/// Decrypted"),
    (r"///\s*已签名", "/// Signed"),
    (r"///\s*已验证", "/// Verified"),
    (r"///\s*已确认", "/// Confirmed"),
    (r"///\s*已拒绝", "/// Rejected"),
    (r"///\s*已批准", "/// Approved"),
    (r"///\s*已审核", "/// Reviewed"),
    (r"///\s*已审计", "/// Audited"),
    (r"///\s*已记录", "/// Logged"),
    (r"///\s*已跟踪", "/// Tracked"),
    (r"///\s*已监控", "/// Monitored"),
    (r"///\s*已报警", "/// Alerted"),
    (r"///\s*已报告", "/// Reported"),
    (r"///\s*已统计", "/// Counted"),
    (r"///\s*已分析", "/// Analyzed"),
    (r"///\s*已评估", "/// Evaluated"),
    (r"///\s*已测试", "/// Tested"),
    (r"///\s*已优化", "/// Optimized"),
    (r"///\s*已简化", "/// Simplified"),
    (r"///\s*已改进", "/// Improved"),
    (r"///\s*已增强", "/// Enhanced"),
    (r"///\s*已扩展", "/// Extended"),
    (r"///\s*已重构", "/// Refactored"),
    (r"///\s*已解决", "/// Resolved"),
    (r"///\s*已完成", "/// Done"),
    (r"///\s*进行中", "/// In progress"),
    (r"///\s*待处理", "/// Pending"),
    (r"///\s*已就绪", "/// Ready"),
    (r"///\s*未就绪", "/// Not ready"),
    (r"///\s*已初始化", "/// Initialized"),
    (r"///\s*已配置", "/// Configured"),
    (r"///\s*已安装", "/// Installed"),
    (r"///\s*已卸载", "/// Uninstalled"),
    (r"///\s*已部署", "/// Deployed"),
    (r"///\s*已迁移", "/// Migrated"),
    (r"///\s*已升级", "/// Upgraded"),
    (r"///\s*已降级", "/// Downgraded"),
    (r"///\s*已启动", "/// Started"),
    (r"///\s*已停止", "/// Stopped"),
    (r"///\s*已暂停", "/// Paused"),
    (r"///\s*已恢复", "/// Resumed"),
    (r"///\s*已重试", "/// Retried"),
    (r"///\s*已中断", "/// Interrupted"),
    (r"///\s*已淘汰", "/// Evicted"),
    (r"///\s*已回收", "/// Reaped"),
    (r"///\s*已清理", "/// Cleaned"),
    (r"///\s*已压缩", "/// Compressed"),
    (r"///\s*已解压", "/// Decompressed"),
    (r"///\s*已打包", "/// Packaged"),
    (r"///\s*已解包", "/// Unpackaged"),
    (r"///\s*已序列化", "/// Serialized"),
    (r"///\s*已反序列化", "/// Deserialized"),
    (r"///\s*已校验", "/// Checksummed"),
    (r"///\s*已摘要", "/// Digested"),
    (r"///\s*已哈希", "/// Hashed"),
    (r"///\s*已脱敏", "/// Desensitized"),
    (r"///\s*已掩码", "/// Masked"),
    (r"///\s*已过滤", "/// Filtered"),
]


def translate_line(line: str) -> tuple[str, bool]:
    """Translate a single rustdoc line. Returns (translated, was_translated)."""
    if not line.lstrip().startswith("///"):
        return line, True

    stripped = line.lstrip()
    prefix = line[: len(line) - len(stripped)]
    content = stripped[3:].lstrip()

    if not re.search(r"[\u4e00-\u9fff]", content):
        return line, True

    for zh, en in TERM_MAP.items():
        content = content.replace(zh, en)

    for pattern, replacement in COMMON_PATTERNS:
        new_content = re.sub(pattern, replacement, content)
        if new_content != content:
            content = new_content

    has_chinese = bool(re.search(r"[\u4e00-\u9fff]", content))
    return prefix + "/// " + content, not has_chinese


def process_file(filepath: Path) -> tuple[int, int]:
    """Process a single file. Returns (total_rustdoc_lines, translated_lines)."""
    text = filepath.read_text(encoding="utf-8", errors="ignore")
    lines = text.split("\n")
    total = 0
    translated = 0
    new_lines = []
    for line in lines:
        if line.lstrip().startswith("///") and re.search(r"[\u4e00-\u9fff]", line):
            total += 1
            new_line, was_translated = translate_line(line)
            if was_translated:
                translated += 1
            new_lines.append(new_line)
        else:
            new_lines.append(line)
    if total > 0:
        filepath.write_text("\n".join(new_lines), encoding="utf-8")
    return total, translated


def main() -> int:
    root = Path("packages")
    files = []
    for f in root.rglob("*.rs"):
        if "\\tests\\" in str(f) or "/tests/" in str(f):
            continue
        if "\\target\\" in str(f) or "/target/" in str(f):
            continue
        files.append(f)

    total_all = 0
    translated_all = 0
    for f in sorted(files):
        total, translated = process_file(f)
        if total > 0:
            total_all += total
            translated_all += translated
            print(f"  {f}: {translated}/{total} translated")

    print(f"\nTotal: {translated_all}/{total_all} lines translated")
    remaining = total_all - translated_all
    print(f"Remaining: {remaining} lines need manual translation")
    return 0


if __name__ == "__main__":
    sys.exit(main())