apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sz-orm
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  database-url: "{{ .Values.database.driver }}://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"