use sz_orm_core::migration::{ColumnDef, ForeignKeyDef, IndexDef, SchemaBuilder};
use sz_orm_core::DbType;

#[test]
fn test_column_def_new() {
    let c = ColumnDef::new("id", "BIGINT");
    assert_eq!(c.name, "id");
    assert_eq!(c.col_type, "BIGINT");
    assert!(c.nullable);
    assert!(!c.auto_increment);
    assert!(!c.unique);
}

#[test]
fn test_column_def_not_null() {
    let c = ColumnDef::new("name", "VARCHAR").not_null();
    assert!(!c.nullable);
}

#[test]
fn test_column_def_default() {
    let c = ColumnDef::new("status", "INT").default("0");
    assert_eq!(c.default, Some("0".to_string()));
}

#[test]
fn test_column_def_auto_increment() {
    let c = ColumnDef::new("id", "BIGINT").auto_increment();
    assert!(c.auto_increment);
}

#[test]
fn test_column_def_unique() {
    let c = ColumnDef::new("email", "VARCHAR").unique();
    assert!(c.unique);
}

#[test]
fn test_column_def_comment() {
    let c = ColumnDef::new("name", "VARCHAR").comment("user name");
    assert_eq!(c.comment, Some("user name".to_string()));
}

#[test]
fn test_column_def_length() {
    let c = ColumnDef::new("name", "VARCHAR").length(255);
    assert_eq!(c.length, Some(255));
}

#[test]
fn test_index_def_new() {
    let i = IndexDef::new("idx_name", vec!["name"]);
    assert_eq!(i.name, "idx_name");
    assert_eq!(i.columns.len(), 1);
    assert!(!i.unique);
}

#[test]
fn test_index_def_unique() {
    let i = IndexDef::new("idx_email", vec!["email"]).unique();
    assert!(i.unique);
}

#[test]
fn test_foreign_key_def_new() {
    let fk = ForeignKeyDef::new("fk_user", "user_id", "users", "id");
    assert_eq!(fk.name, "fk_user");
    assert_eq!(fk.column, "user_id");
    assert_eq!(fk.referenced_table, "users");
    assert_eq!(fk.referenced_column, "id");
    assert!(fk.on_delete.is_none());
    assert!(fk.on_update.is_none());
}

#[test]
fn test_foreign_key_def_on_delete() {
    let fk = ForeignKeyDef::new("fk_user", "user_id", "users", "id").on_delete("CASCADE");
    assert_eq!(fk.on_delete, Some("CASCADE".to_string()));
}

#[test]
fn test_foreign_key_def_on_update() {
    let fk = ForeignKeyDef::new("fk_user", "user_id", "users", "id").on_update("SET NULL");
    assert_eq!(fk.on_update, Some("SET NULL".to_string()));
}

#[test]
fn test_schema_builder_new() {
    let sb = SchemaBuilder::new("users");
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("CREATE TABLE IF NOT EXISTS users"));
}

#[test]
fn test_schema_builder_with_column() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("id", "BIGINT").not_null().auto_increment())
        .add_column(ColumnDef::new("name", "VARCHAR").not_null());
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("id BIGINT AUTO_INCREMENT NOT NULL"));
    assert!(sql.contains("name VARCHAR NOT NULL"));
}

#[test]
fn test_schema_builder_with_index() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("id", "BIGINT").not_null())
        .add_index(IndexDef::new("idx_id", vec!["id"]));
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("KEY idx_id (id)"));
}

#[test]
fn test_schema_builder_with_unique_index() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("email", "VARCHAR").not_null())
        .add_index(IndexDef::new("idx_email", vec!["email"]).unique());
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("UNIQUE KEY idx_email (email)"));
}

#[test]
fn test_schema_builder_with_foreign_key() {
    let sb = SchemaBuilder::new("posts")
        .add_column(ColumnDef::new("user_id", "BIGINT").not_null())
        .add_foreign_key(
            ForeignKeyDef::new("fk_user", "user_id", "users", "id").on_delete("CASCADE"),
        );
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id)"));
    assert!(sql.contains("ON DELETE CASCADE"));
}

#[test]
fn test_schema_builder_if_not_exists_false() {
    let sb = SchemaBuilder::new("users").if_not_exists(false);
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(!sql.contains("IF NOT EXISTS"));
}

#[test]
fn test_schema_builder_pg_auto_increment() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("id", "BIGINT").not_null().auto_increment());
    let sql = sb.build(DbType::PostgreSQL).unwrap();
    assert!(sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
}

#[test]
fn test_schema_builder_sqlite_auto_increment() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("id", "BIGINT").not_null().auto_increment());
    let sql = sb.build(DbType::Sqlite).unwrap();
    assert!(sql.contains("AUTOINCREMENT"));
}

#[test]
fn test_schema_builder_column_with_default() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("status", "INT").not_null().default("1"));
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("DEFAULT 1"));
}

#[test]
fn test_schema_builder_column_with_length_mysql() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("name", "VARCHAR").length(255).not_null());
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("VARCHAR(255)"));
}

#[test]
fn test_schema_builder_column_unique() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("email", "VARCHAR").not_null().unique());
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("UNIQUE"));
}

#[test]
fn test_schema_builder_multiple_columns() {
    let sb = SchemaBuilder::new("users")
        .add_column(ColumnDef::new("id", "BIGINT").not_null())
        .add_column(ColumnDef::new("name", "VARCHAR").not_null())
        .add_column(ColumnDef::new("email", "VARCHAR").not_null());
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("id BIGINT NOT NULL"));
    assert!(sql.contains("name VARCHAR NOT NULL"));
    assert!(sql.contains("email VARCHAR NOT NULL"));
}

#[test]
fn test_foreign_key_def_on_delete_set_null() {
    let sb = SchemaBuilder::new("posts")
        .add_column(ColumnDef::new("user_id", "BIGINT"))
        .add_foreign_key(
            ForeignKeyDef::new("fk_user", "user_id", "users", "id").on_delete("SET NULL"),
        );
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("ON DELETE SET NULL"));
}

#[test]
fn test_foreign_key_def_on_update_cascade() {
    let sb = SchemaBuilder::new("posts")
        .add_column(ColumnDef::new("user_id", "BIGINT"))
        .add_foreign_key(
            ForeignKeyDef::new("fk_user", "user_id", "users", "id").on_update("CASCADE"),
        );
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("ON UPDATE CASCADE"));
}

#[test]
fn test_schema_builder_empty_columns() {
    let sb = SchemaBuilder::new("empty");
    let sql = sb.build(DbType::MySQL).unwrap();
    assert!(sql.contains("CREATE TABLE IF NOT EXISTS empty ()"));
}
